 # Pandapower with UK Power Networks

This tutorial shows some functionalities and studies that can be performed using the power flow capabilities of pandapower. It will demonstrate how to run power flow simulations in pandapower, how to analyse the grid and to investigate different use cases relying on the power flow engine of pandapower.

This tutorial has been created in collaboration with UK Power Networks, the Distribution System Operator owning and operating the electricity network across London, the South East and the East of England.

The tutorial will use the real grids associated with the three licensed electricity distribution networks operated by UKPN (LPN, SPN and EPN). It will provide some examples of how pandapower can be used to run investigations and analyses using the open source data released by UK Power Networks. UK Power Networks has provided this grid data as part of their LTDS CIM dataset release. It is a "Shared" dataset that requires special access. To request access:

·       Register and login to [UK Power Networks' Open Data Portal](https://ukpowernetworks.opendatasoft.com/pages/home/)

·       Visit [the LTDS CIM page](https://ukpowernetworks.opendatasoft.com/explore/assets/ukpn-ltds-cim/) and complete [the Shared Data Request Form](https://ukpowernetworks.opendatasoft.com/explore/forms/cim-access-request-form/)



Once approved, CIM data is published as XML file attachments (one per licence area: EPN, SPN, LPN). You can download the XML files directly from the portal.

Import the pandapower library and the neccessary methods for the conversion as follows:

In [201]:
import os
import pandapower as pp
from pandapower.converter.cim import from_cim as cim2pp
from pandapower.converter.cim.cim_classes import CimParser
import pandas as pd
import numpy as np
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=pd.errors.SettingWithCopyWarning)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)
pd.options.display.float_format = '{:,.4f}'.format

## LTDS to pandapower

First, we define the LTDS zip archive, which can be converted to pandapower. If there is no SSH profile available, there is an option to get the generation and load data from LTDS Tables. However, please take into account that there are some assumptions made, which limit the applicability of the data and make them unsuitable for all use cases.

Note: For this tutorial, the network data is imported via the LTDS CIM file, while demand and generation data are derived from LTDS Table 3A – Observed Load and Table 5 – Generation. To enable proper matching of substations in LTDS CIM, these tables have been improved by populating a new MRID column, which provides a unique identification number in CIM. These files are available in the folder where the CIM data was shared.

In [ ]:
# ltds_files is a list containing paths to files needed for the LTDS converter:
ltds_files = "LTDS_LPN_2025_02_EQ_2025-11-28_v1.0.zip"          # Provide the correct directory for the LTDS CIM file
path_excel_demand = "ltds-table-3a-load-data-observed.xlsx"     # Provide the correct directory for the load table
path_excel_generation = "ltds-table-5-generation.xlsx"          # Provide the correct directory for the generation table
excel_column_name = 'Maximum_Demand_24_25_MW'
excel_column_name_pf = 'Maximum_Demand_24_25_PF'
# the Excel data provides the maximum demand / generation. If you want to assume a specific loading,
# choose a scaling_factor between 0.1 and 1.0
scaling_factor = 1.0

cim_parser = CimParser(cgmes_version='ltds')
cim_parser.parse_files(ltds_files).prepare_cim_net().set_cim_data_types()
cim = cim_parser.cim

excel_df_demand = pd.read_excel(path_excel_demand, sheet_name='Feuil1', skiprows=0)
excel_df_generation = pd.read_excel(path_excel_generation, sheet_name='Feuil1', skiprows=0)

In [203]:
def format_uuid_no_dash(uuid_no_dash: str) -> str | None:
    if uuid_no_dash is None:
        return None
    s = str(uuid_no_dash).lstrip("_")
    if len(s) != 32:
        return uuid_no_dash
    parts = [s[0:8], s[8:12], s[12:16], s[16:20], s[20:32]]
    return '_' + '-'.join(parts)
# prepare the demand data
if not excel_df_demand.empty:
    if 'Season' in excel_df_demand:
        excel_df_demand = excel_df_demand.loc[excel_df_demand['Season'] == 'Winter']
    excel_df_demand = excel_df_demand.rename(columns={'Substation MRID': 'name_excel', excel_column_name: 'p_mw_excel', excel_column_name_pf: 'q_mvar_excel'})
    if 'name_excel' not in excel_df_demand or 'p_mw_excel' not in excel_df_demand or 'q_mvar_excel' not in excel_df_demand:
        # the Excel document is not valid
        excel_df_demand = pd.DataFrame(columns=['name_excel', 'p_mw_excel', 'q_mvar_excel'])
    excel_df_demand = excel_df_demand[['name_excel', 'p_mw_excel', 'q_mvar_excel']].copy()
    excel_df_demand['p_mw_excel'] = excel_df_demand['p_mw_excel'].astype(float)
    excel_df_demand['q_mvar_excel'] = excel_df_demand['q_mvar_excel'].astype(float)
    excel_df_demand['q_mvar_excel'] = ((excel_df_demand['p_mw_excel'] / excel_df_demand['q_mvar_excel'])**2 - excel_df_demand['p_mw_excel']**2)**.5
    excel_df_demand = excel_df_demand.dropna(how='any')
    excel_df_demand_orig = excel_df_demand.copy()
    excel_df_demand = excel_df_demand_orig.groupby('name_excel', as_index=False)['p_mw_excel'].sum()
    excel_df_demand['q_mvar_excel'] = excel_df_demand_orig.groupby('name_excel', as_index=False)['q_mvar_excel'].sum()['q_mvar_excel']
else:
    excel_df_demand = pd.DataFrame(columns=['name_excel', 'p_mw_excel', 'q_mvar_excel'])
# prepare the generation data
if not excel_df_generation.empty:
    if 'Connected_Accepted' in excel_df_generation:
        excel_df_generation = excel_df_generation.loc[excel_df_generation['Connected_Accepted'] == 'Connected']
    excel_df_generation = excel_df_generation.rename(columns={'Substation MRID': 'name_excel', 'InstalledCapacity_MVA': 'p_mw_excel'})
    if 'name_excel' not in excel_df_generation or 'p_mw_excel' not in excel_df_generation:
        # the Excel document is not valid
        excel_df_generation = pd.DataFrame(columns=['name_excel', 'p_mw_excel'])
    excel_df_generation['p_mw_excel'] = excel_df_generation['p_mw_excel'].astype(float)
    excel_df_generation['p_mw_excel'] = excel_df_generation['p_mw_excel'] * -1
    excel_df_generation = excel_df_generation.dropna(how='any')
    # note: there might be an issue with the UUID format, this will be fixed with the following line:
    excel_df_generation['name_excel'] = excel_df_generation['name_excel'].apply(format_uuid_no_dash)

    excel_df_generation = excel_df_generation.groupby('name_excel', as_index=False)['p_mw_excel'].sum()
else:
    excel_df_generation = pd.DataFrame(columns=['name_excel', 'p_mw_excel'])

# add the loads to the SSH profile
cim['ssh']['EnergyConsumer'] = pd.concat([cim['ssh']['EnergyConsumer'], cim['eq']['EnergyConsumer'][['rdfId']]], ignore_index=True)
# get the Substation ID
sub = cim['eq']['Terminal'][['ConnectivityNode', 'ConductingEquipment']]
sub = sub.rename(columns={'ConnectivityNode': 'rdfId'})
sub = pd.merge(sub, cim['eq']['ConnectivityNode'][['rdfId', 'ConnectivityNodeContainer']], how='left', on='rdfId')
sub = sub.drop(columns=['rdfId']).drop_duplicates(subset=['ConductingEquipment'])
# adding substations to EnergyConsumer
cim['ssh']['EnergyConsumer']['sub'] = cim['ssh']['EnergyConsumer']['rdfId'].map(
    sub.set_index('ConductingEquipment')['ConnectivityNodeContainer'])
# identify duplications
cim['ssh']['EnergyConsumer']['dups'] = cim['ssh']['EnergyConsumer'].groupby('sub')['sub'].transform('count')
cim['ssh']['EnergyConsumer']['p'] = cim['ssh']['EnergyConsumer']['sub'].map(
    excel_df_demand.set_index('name_excel')['p_mw_excel']) / cim['ssh']['EnergyConsumer']['dups']
cim['ssh']['EnergyConsumer']['p'] = cim['ssh']['EnergyConsumer']['p'].fillna(0.) * scaling_factor
cim['ssh']['EnergyConsumer']['q'] = cim['ssh']['EnergyConsumer']['sub'].map(
    excel_df_demand.set_index('name_excel')['q_mvar_excel']) / cim['ssh']['EnergyConsumer']['dups']
cim['ssh']['EnergyConsumer']['q'] = cim['ssh']['EnergyConsumer']['q'].fillna(0.)
cim['ssh']['EnergyConsumer']['inService'] = cim['ssh']['EnergyConsumer']['inService'].fillna(True)
cim['ssh']['EnergyConsumer'] = cim['ssh']['EnergyConsumer'].drop(columns=['sub', 'dups'])

# add the generation to the SSH profile
for one_asset in ['SynchronousMachine', 'PowerElectronicsConnection']:
    cim['ssh'][one_asset] = pd.concat([cim['ssh'][one_asset], cim['eq'][one_asset][['rdfId']]], ignore_index=True)
    # adding substations to generators
    cim['ssh'][one_asset]['sub'] = cim['ssh'][one_asset]['rdfId'].map(sub.set_index('ConductingEquipment')['ConnectivityNodeContainer'])
    # identify duplications
    cim['ssh'][one_asset]['dups'] = cim['ssh'][one_asset].groupby('sub')['sub'].transform('count')
    cim['ssh'][one_asset]['p'] = cim['ssh'][one_asset]['sub'].map(
        excel_df_generation.set_index('name_excel')['p_mw_excel']) / cim['ssh'][one_asset]['dups']
    cim['ssh'][one_asset]['p'] = cim['ssh'][one_asset]['p'].fillna(0.) * scaling_factor
    cim['ssh'][one_asset]['q'] = cim['ssh'][one_asset]['q'].fillna(0.)
    cim['ssh'][one_asset]['inService'] = cim['ssh'][one_asset]['inService'].fillna(True)
    cim['ssh'][one_asset] = cim['ssh'][one_asset].drop(columns=['sub', 'dups'])

for one_sw in ['Breaker', 'Disconnector', 'Switch', 'LoadBreakSwitch']:
    cim['ssh'][one_sw] = pd.concat([cim['ssh'][one_sw], cim['eq'][one_sw][['rdfId', 'normalOpen']].rename(columns={'normalOpen': 'open'})], ignore_index=True)
    cim['ssh'][one_sw]['inService'] = True

for one_asset in ['ExternalNetworkInjection', 'ConformLoad', 'NonConformLoad', 'StationSupply',
                  'AsynchronousMachine', 'EquivalentInjection']:
    cim['ssh'][one_asset] = pd.concat([cim['ssh'][one_asset], cim['eq'][one_asset][['rdfId']]], ignore_index=True)
    cim['ssh'][one_asset]['p'] = cim['ssh'][one_asset]['p'].fillna(0.) * scaling_factor
    cim['ssh'][one_asset]['q'] = cim['ssh'][one_asset]['q'].fillna(0.)
    cim['ssh'][one_asset]['inService'] = cim['ssh'][one_asset]['inService'].fillna(True)

cim['ssh']['ExternalNetworkInjection']['referencePriority'] = cim['ssh']['ExternalNetworkInjection']['referencePriority'].fillna(1)
cim['ssh']['ExternalNetworkInjection']['controlEnabled'] = cim['ssh']['ExternalNetworkInjection']['controlEnabled'].fillna(True)
cim['ssh']['SynchronousMachine']['referencePriority'] = cim['ssh']['SynchronousMachine']['referencePriority'].fillna(0)
cim['ssh']['SynchronousMachine']['controlEnabled'] = cim['ssh']['SynchronousMachine']['controlEnabled'].fillna(False)
cim['ssh']['EquivalentInjection']['regulationStatus'] = cim['ssh']['EquivalentInjection']['regulationStatus'].fillna(False)

cim['ssh']['EnergySource'] = pd.concat([cim['ssh']['EnergySource'], cim['eq']['EnergySource'][['rdfId']]], ignore_index=True)
cim['ssh']['EnergySource']['activePower'] = cim['ssh']['EnergySource']['activePower'].fillna(0.)
cim['ssh']['EnergySource']['reactivePower'] = cim['ssh']['EnergySource']['reactivePower'].fillna(0.)
cim['ssh']['EnergySource']['inService'] = cim['ssh']['EnergySource']['inService'].fillna(True)

cim['ssh']['StaticVarCompensator'] = pd.concat([cim['ssh']['StaticVarCompensator'], cim['eq']['StaticVarCompensator'][['rdfId']]], ignore_index=True)
cim['ssh']['StaticVarCompensator']['q'] = cim['ssh']['StaticVarCompensator']['q'].fillna(0.)
cim['ssh']['StaticVarCompensator']['inService'] = cim['ssh']['StaticVarCompensator']['inService'].fillna(True)

# add the terminals
cim['ssh']['Terminal'] = pd.concat([cim['ssh']['Terminal'], cim['eq']['Terminal'][['rdfId']]], ignore_index=True)
cim['ssh']['Terminal']['connected'] = cim['ssh']['Terminal']['connected'].fillna(True)
# add the shunts
cim['ssh']['LinearShuntCompensator'] = pd.concat([cim['ssh']['LinearShuntCompensator'], cim['eq']['LinearShuntCompensator'][['rdfId', 'normalSections']].rename(
    columns={'normalSections': 'sections'})], ignore_index=True)
cim['ssh']['LinearShuntCompensator']['controlEnabled'] = cim['ssh']['LinearShuntCompensator']['controlEnabled'].fillna(False)
cim['ssh']['LinearShuntCompensator']['inService'] = cim['ssh']['LinearShuntCompensator']['inService'].fillna(True)
cim['ssh']['NonlinearShuntCompensator'] = pd.concat([cim['ssh']['NonlinearShuntCompensator'], cim['eq']['NonlinearShuntCompensator'][['rdfId']]], ignore_index=True)
cim['ssh']['NonlinearShuntCompensator']['sections'] = cim['ssh']['NonlinearShuntCompensator']['sections'].fillna(0)
cim['ssh']['NonlinearShuntCompensator']['controlEnabled'] = cim['ssh']['NonlinearShuntCompensator']['controlEnabled'].fillna(False)
cim['ssh']['NonlinearShuntCompensator']['inService'] = cim['ssh']['NonlinearShuntCompensator']['inService'].fillna(True)

# add the tap changer steps
cim['ssh']['RatioTapChanger'] = pd.concat([cim['ssh']['RatioTapChanger'], cim['eq']['RatioTapChanger'][['rdfId', 'neutralStep']].rename(
    columns={'neutralStep': 'step'})], ignore_index=True)
cim['ssh']['RatioTapChanger']['controlEnabled'] = cim['ssh']['RatioTapChanger']['controlEnabled'].fillna(False)
# add the TapChangerControls
cim['ssh']['TapChangerControl'] = pd.concat([cim['ssh']['TapChangerControl'], cim['eq']['TapChangerControl'][['rdfId']]], ignore_index=True)
cim['ssh']['TapChangerControl']['discrete'] = cim['ssh']['TapChangerControl']['discrete'].fillna(False)
cim['ssh']['TapChangerControl']['enabled'] = cim['ssh']['TapChangerControl']['enabled'].fillna(False)
cim['eq']['PowerTransformer']['inService'] = True

cim['ssh']['Equipment'] = pd.concat([cim['ssh']['Equipment'], cim['eq']['EquivalentBranch'][['rdfId']]], ignore_index=True)
cim['ssh']['Equipment']['inService'] = cim['ssh']['Equipment']['inService'].fillna(True)
cim['ssh']['Equipment'] = pd.concat([cim['ssh']['Equipment'], cim['eq']['ACLineSegment'][['rdfId']]], ignore_index=True)
cim['ssh']['Equipment']['inService'] = cim['ssh']['Equipment']['inService'].fillna(True)
cim['ssh']['Equipment'] = pd.concat([cim['ssh']['Equipment'], cim['eq']['DCLineSegment'][['rdfId']]], ignore_index=True)
cim['ssh']['Equipment']['inService'] = cim['ssh']['Equipment']['inService'].fillna(True)

# use the from_cim_dict to put in the modified CimParser
net = cim2pp.from_cim_dict(cim_parser=cim_parser, cim_version='LTDS', create_tap_controller=False)

# if there is no slack in the grid, create one
if net.gen.empty and net.ext_grid.empty and not net.sgen.empty:
    slack = net.sgen.loc[net.sgen.in_service].loc[net.sgen.p_mw == net.sgen.p_mw.max()]
    net.sgen = net.sgen.drop(slack.index[0])
    pp.create_gen(net, bus=slack.bus.iloc[0], p_mw=slack.p_mw.iloc[0], slack=True, in_service=True)

print('Conversion successful')

Conversion successful

## Get an overview over your grid
Once the network is converted to pandapower, the data can be displayed:

In [204]:
print(net)

This pandapower network includes the following parameter tables:
   - bus (10746 elements)
   - load (2892 elements)
   - sgen (7 elements)
   - gen (1 element)
   - switch (13289 elements)
   - shunt (14 elements)
   - line (944 elements)
   - trafo (485 elements)
   - trafo3w (97 elements)
   - impedance (100 elements)
   - ward (77 elements)

## Export your grid
There are different options to export, for example as JSON, Excel or CSV:

In [ ]:
path_to_json = "UKPN_grid.json"
path_to_excel = "UKPN_grid.xlsx"
pp.to_json(net, path_to_json)
pp.to_excel(net, path_to_excel)

Could not serialize net.CGMES
Could not serialize net.report_container

In [ ]:
net.line.to_excel("line_data.xlsx")
net.trafo.to_excel("trafo_data.xlsx")
net.bus.to_excel("bus_data.xlsx")

## Display the nodes

In [207]:
print(net.bus.iloc[0])

name                                                             T_39
vn_kv                                                        132.0000
type                                                                n
zone                                                    Wimbledon 3&4
in_service                                                       True
geo                                                               NaN
origin_id                       _ef8b046a-870d-4c83-9071-da2f0ebec399
origin_class                                         ConnectivityNode
origin_profile                                                     eq
cim_topnode                                                       NaN
ConnectivityNodeContainer_id    _d3a9e549-ea05-4ab2-8e5a-d45ee4ad53ca
Substation_id                   _d2d3ea2c-a4e0-4d3b-9fb6-aae460f2ef3a
description                                                       NaN
Busbar_id                                                         NaN
Busbar_name                                                       NaN
GeographicalRegion_id           _01939da8-90b4-4a6b-bf39-d6008aedb166
GeographicalRegion_name                                      DNO-UKPN
SubGeographicalRegion_id        _dcf403f4-5966-477d-ad33-ca6a38c4be15
SubGeographicalRegion_name               21 - Wimbledon 3&4 132kV GSP
Name: 0, dtype: object

## Display the lines

In [208]:
print(net.line.iloc[0])

name                                           lne_BRWB_WFCS_1
std_type                                                  None
from_bus                                                  6160
to_bus                                                    7589
length_km                                               2.1750
r_ohm_per_km                                            0.1290
x_ohm_per_km                                            0.1260
c_nf_per_km                                           142.0009
g_us_per_km                                             0.0000
max_i_ka                                                   NaN
df                                                      1.0000
parallel                                                     1
type                                                      None
in_service                                                True
geo                                                        NaN
origin_id                _00122e74-780a-493b-904b-37dfffb0a19a
origin_class                                     ACLineSegment
terminal_from            _25c5c127-3c60-a41e-1310-caaec253043b
terminal_to              _8fe19d17-aa29-1d2b-5a5c-e96d86a8bb77
description                                                NaN
EquipmentContainer_id    _7d39d856-173c-adc6-2001-648d6e40d7ee
r0_ohm_per_km                                              NaN
x0_ohm_per_km                                              NaN
c0_nf_per_km                                               NaN
g0_us_per_km                                               NaN
endtemp_degree                                             NaN
Name: 0, dtype: object

## Display the transformers

In [209]:
# two winding transformers
print(net.trafo.iloc[0])

name                                                                             T4
std_type                                                                       None
hv_bus                                                                         7874
lv_bus                                                                         8511
sn_mva                                                                      10.0000
vn_hv_kv                                                                    22.0000
vn_lv_kv                                                                     6.6000
vk_percent                                                                  11.2956
vkr_percent                                                                  0.7600
pfe_kw                                                                       0.0000
i0_percent                                                                   0.0000
shift_degree                                                                 0.0000
tap_side                                                                         hv
tap_neutral                                                                       0
tap_min                                                                          -6
tap_max                                                                           6
tap_step_percent                                                             1.3333
tap_step_degree                                                                 NaN
tap_pos                                                                           0
tap_changer_type                                                              Ratio
id_characteristic_table                                                        <NA>
tap_dependency_table                                                          False
parallel                                                                          1
df                                                                           1.0000
in_service                                                                     True
origin_id                                     _01466a4c-b8b3-47be-91ee-64dcf2db4f0a
origin_class                                                       PowerTransformer
terminal_hv                                   _8b66f2df-d3bf-c694-e1cf-af123e827be3
terminal_lv                                   _2bb600a5-2e44-ad5d-d8d2-86dfe0a1cf28
PowerTransformerEnd_id_hv                     _527d3a54-bf55-3fba-cb31-1e2cd732ff4d
PowerTransformerEnd_id_lv                     _08e0376a-81bd-a982-3c65-499bde0422d1
tapchanger_class                                                    RatioTapChanger
tapchanger_id                                 _4ae25d88-65e7-be1e-1753-5016a482853d
tapchanger2_class                                                               NaN
tapchanger2_id                                                                  NaN
tap2_changer_type                                                               NaN
tap2_side                                                                      None
description                                                                     NaN
vector_group                                                                    Dyn
OperationalLimitType.limitType_hv                                               NaN
OperationalLimitType.limitType_lv                                               NaN
tap2_neutral                                                                   <NA>
tap2_min                                                                       <NA>
tap2_max                                                                       <NA>
tap2_pos                                                                       <NA>
tap2_step_percent                                                               NaN
tap2_step_degree                                                                NaN
vk0_percent                                                                     NaN
vkr0_percent                                                                    NaN
xn_ohm                                                                          NaN
CurrentLimit.value_hv                                                           NaN
CurrentLimit.value_lv                                                           NaN
OperationalLimitType.acceptableDuration_hv                                      NaN
OperationalLimitType.acceptableDuration_lv                                      NaN
power_station_unit                                                             <NA>
oltc                                                                           True
Name: 0, dtype: object

In [210]:
# three winding transformers
print(net.trafo3w.iloc[0])

name                                                                            GT1
std_type                                                                       None
hv_bus                                                                         9001
mv_bus                                                                        10064
lv_bus                                                                         2409
sn_hv_mva                                                                   60.6000
sn_mv_mva                                                                   30.3000
sn_lv_mva                                                                   30.3000
vn_hv_kv                                                                   132.0000
vn_mv_kv                                                                    11.1100
vn_lv_kv                                                                    11.1100
vk_hv_percent                                                               31.8601
vk_mv_percent                                                               52.1400
vk_lv_percent                                                               31.9099
vkr_hv_percent                                                               0.7172
vkr_mv_percent                                                               1.7010
vkr_lv_percent                                                               0.7287
pfe_kw                                                                      19.1201
i0_percent                                                                   0.0684
shift_mv_degree                                                              0.0000
shift_lv_degree                                                              0.0000
tap_side                                                                         hv
tap_neutral                                                                       6
tap_min                                                                           1
tap_max                                                                          19
tap_step_percent                                                            -1.8500
tap_step_degree                                                                 NaN
tap_pos                                                                           6
tap_at_star_point                                                             False
tap_changer_type                                                              Ratio
id_characteristic_table                                                        <NA>
tap_dependency_table                                                          False
in_service                                                                     True
origin_id                                     _01404308-0d21-457b-8332-5b109e518a13
origin_class                                                       PowerTransformer
terminal_hv                                   _293706d3-b086-ec2b-85ef-153b05d315c0
terminal_mv                                   _1090d6da-8b2d-607c-18b0-cc1dddcc5cf2
terminal_lv                                   _f59133bf-2543-c9d2-f0b1-661ecc910496
PowerTransformerEnd_id_hv                     _60155eee-702c-b01d-9437-8164226cbbf6
PowerTransformerEnd_id_mv                     _59f440f6-d77b-e685-fe65-0f69196a1572
PowerTransformerEnd_id_lv                     _76cf20ff-a597-cc9b-7551-93a13de2f337
tapchanger_class                                                    RatioTapChanger
tapchanger_id                                 _ea326a47-6ae7-ccc2-92be-281be4878f4a
description                                                                     NaN
vector_group                                                                 YNynyn
OperationalLimitType.limitType_hv                                               NaN
OperationalLimitType.limitType_mv                                               NaN
OperationalLimitType.limitType_lv                                               NaN
vk0_hv_percent                                                                  NaN
vk0_mv_percent                                                                  NaN
vk0_lv_percent                                                                  NaN
vkr0_hv_percent                                                                 NaN
vkr0_mv_percent                                                                 NaN
vkr0_lv_percent                                                                 NaN
CurrentLimit.value_hv                                                           NaN
CurrentLimit.value_mv                                                           NaN
CurrentLimit.value_lv                                                           NaN
OperationalLimitType.acceptableDuration_hv                                      NaN
OperationalLimitType.acceptableDuration_mv                                      NaN
OperationalLimitType.acceptableDuration_lv                                      NaN
power_station_unit                                                             <NA>
Name: 0, dtype: object

## Display the loads

In [211]:
print(net.load.iloc[0])

name                                                    W2
bus                                                   7547
p_mw                                                1.8105
q_mvar                                              0.4538
const_z_p_percent                                   0.0000
const_i_p_percent                                   0.0000
const_z_q_percent                                   0.0000
const_i_q_percent                                   0.0000
sn_mva                                                 NaN
scaling                                             1.0000
in_service                                            True
type                                                  None
origin_id            _001042be-8d96-4f41-bcea-c835cdac77fb
origin_class                                EnergyConsumer
terminal             _172fc73f-33ec-9899-2c3b-66203a28cc94
description                                            NaN
Name: 0, dtype: object

## Display the generation

In [212]:
print(net.sgen.iloc[0])

name                                                       LPN 0007(27)
bus                                                                4495
p_mw                                                            -0.0000
q_mvar                                                          -0.0000
min_q_mvar                                                          NaN
max_q_mvar                                                          NaN
sn_mva                                                              NaN
scaling                                                          1.0000
controllable                                                      False
id_q_capability_characteristic                                     <NA>
reactive_capability_curve                                           NaN
curve_style                                                         NaN
in_service                                                         True
type                                                     GeneratingUnit
current_source                                                     True
origin_id                         _2e145bd5-8cf9-417f-a83b-9dce5818a924
origin_class                                         SynchronousMachine
terminal                          _3e043762-1847-9d3b-99a2-2fbc69a8bbb6
description                                                         NaN
generator_type                                           current_source
RegulatingControl.mode                                              NaN
k                                                                   NaN
rx                                                                  NaN
vn_kv                                                               NaN
rdss_ohm                                                            NaN
xdss_pu                                                             NaN
lrc_pu                                                              NaN
RegulatingControl.targetValue                                       NaN
referencePriority                                                0.0000
max_p_mw                                                            NaN
min_p_mw                                                            NaN
RegulatingControl.enabled                                          <NA>
Name: 1, dtype: object

## Get only HV elements from the grid
In pandapower we are using pandas DataFrames, you can create your queries like you wish. Here is an example to get HV (110kV) elements from your grid.

In [213]:
print("the HV nodes first")
print(net.bus.loc[(net.bus.vn_kv > 100) & (net.bus.vn_kv < 150)])

the HV nodes first
                   name    vn_kv type                zone  in_service  geo  \
0                  T_39 132.0000    n       Wimbledon 3&4        True  NaN
16      CITY11 M BB1(2) 132.0000    n           City Road        True  NaN
45      DEPT11 BB3_2(2) 132.0000    n       Deptford Grid        True  NaN
54            HURS12(1) 132.0000    n               Hurst        True  NaN
58            HURS11(1) 132.0000    n               Hurst        True  NaN
76          Terminal(7) 132.0000    n            Bankside        True  NaN
78                  T_5 132.0000    n      Kingston (SPN)        True  NaN
79         HASC11 R BB2 132.0000    b   Hackney Supergrid        True  NaN
81               T_8(1) 132.0000    n   Brunswick Wharf B        True  NaN
96               EBBR12 132.0000    n        Ebury Bridge        True  NaN
104           HOLL11(2) 132.0000    n            Holloway        True  NaN
105     NEWC11 M BB1(5) 132.0000    n     New Cross 132kV        True  NaN
114           LIMA12(1) 132.0000    n       Limeburner LN        True  NaN
119              BEEB13 132.0000    n            Beech St        True  NaN
122             T_54(3) 132.0000    n       St.Johns Wood        True  NaN
137     HASC11 M BB1(5) 132.0000    n   Hackney Supergrid        True  NaN
141     WHAG12 R BB2(7) 132.0000    n            West Ham        True  NaN
144    Term_LIKP2/NFLE3 132.0000    n         Littlebrook        True  NaN
152              DUST11 132.0000    n           Duke St B        True  NaN
156                T_44 132.0000    n           City Road        True  NaN
185           FINE12(1) 132.0000    n     Finsbury Market        True  NaN
187       SYDP12 MC3(2) 132.0000    n       Sydenham Park        True  NaN
195         Terminal(2) 132.0000    n           City Road        True  NaN
196    SJWB11 R BB4(13) 132.0000    n       St.Johns Wood        True  NaN
201              CALS12 132.0000    n          Calshot St        True  NaN
212                 T_9 132.0000    n   Brunswick Wharf B        True  NaN
244     ELTH12 R BB2(7) 132.0000    n         Eltham Grid        True  NaN
255             Term_03 132.0000    n         Littlebrook        True  NaN
258           BROM12(1) 132.0000    b        Bromley Grid        True  NaN
284     BRWB11 M BB2(2) 132.0000    n   Brunswick Wharf B        True  NaN
300    SJWB12 R BB3(10) 132.0000    n       St.Johns Wood        True  NaN
306         Terminal(1) 132.0000    n            Bankside        True  NaN
323    NEWC11 R BB2(12) 132.0000    n     New Cross 132kV        True  NaN
345              T_9(1) 132.0000    n   Brunswick Wharf B        True  NaN
382           BANF10(1) 132.0000    n            Bankside        True  NaN
386             Cub_1.1 132.0000    n      Kingston (SPN)        True  NaN
393     ISLG11 R BB2(3) 132.0000    n           Islington        True  NaN
394              HOLL1C 132.0000    n            Holloway        True  NaN
401     WIML11 M BB1(1) 132.0000    n       Wimbledon 1&2        True  NaN
402     WISD11 M BB2(5) 132.0000    n    Willesden 132 kV        True  NaN
423             T_49(1) 132.0000    n                 Bow        True  NaN
431        SJWB11 M BB4 132.0000    b       St.Johns Wood        True  NaN
439              NPBR11 132.0000    n            LPN 0039        True  NaN
442           CALS11(1) 132.0000    n          Calshot St        True  NaN
446       1030 BACA1T4A 132.0000    n           Back Hill        True  NaN
447           LEIR12(1) 132.0000    n        Leicester Rd        True  NaN
465     DEPT11 BB3_2(4) 132.0000    n       Deptford Grid        True  NaN
480              MANS12 132.0000    n            LPN 0012        True  NaN
482     WIMB12 M BB3(1) 132.0000    b       Wimbledon 3&4        True  NaN
488           LIMA11(4) 132.0000    n       Limeburner LN        True  NaN
490        CITY11 M BB2 132.0000    b           City Road        True  NaN
493           LIMA12(2) 132.0000    n       Limeburner LN        True  NaN
499     WHAG12 R BB1(2) 132.0000    n            West Ham        True  NaN
516     BANF11 R BB2(5) 132.0000    b            Bankside        True  NaN
538     WISD11 M BB2(3) 132.0000    n    Willesden 132 kV        True  NaN
556     NEWC11 R BB2(2) 132.0000    n     New Cross 132kV        True  NaN
567       8030 FULC1T3_ 132.0000    n  Fulham Palace Rd C        True  NaN
571             T_24(4) 132.0000    n       St.Johns Wood        True  NaN
576           BEDD12(1) 132.0000    b          Beddington        True  NaN
620     CITY12 R BB1(6) 132.0000    n           City Road        True  NaN
644           BARK10(4) 132.0000    n         Barking GIS        True  NaN
651        HASC11 M BB1 132.0000    b   Hackney Supergrid        True  NaN
668        Terminal(30) 132.0000    b   Hackney Supergrid        True  NaN
675           BANF10(2) 132.0000    b            Bankside        True  NaN
693              BAND11 132.0000    n            Bankside        True  NaN
699     ELTH12 R BB2(6) 132.0000    n         Eltham Grid        True  NaN
706        BANF11 M BB1 132.0000    b            Bankside        True  NaN
736     SJOW12 M BB1(1) 132.0000    n       St.Johns Wood        True  NaN
749     SJOW12 M BB2(2) 132.0000    n       St.Johns Wood        True  NaN
755              WIMC14 132.0000    b       Wimbledon 3&4        True  NaN
764     CITY12 R BB1(1) 132.0000    b           City Road        True  NaN
792            Terminal 132.0000    n           Brimsdown        True  NaN
794           BENW12(2) 132.0000    b       Bengeworth Rd        True  NaN
805              HOLL12 132.0000    n            Holloway        True  NaN
811        SJOW11 R BB1 132.0000    b       St.Johns Wood        True  NaN
815        NEWC11 M BB2 132.0000    b     New Cross 132kV        True  NaN
819              VISC11 132.0000    n         Victoria St        True  NaN
842        SJOW11 R BB2 132.0000    b       St.Johns Wood        True  NaN
845         Terminal(5) 132.0000    n            Bankside        True  NaN
851            T_23(18) 132.0000    n         Littlebrook        True  NaN
875        SJWB12 R BB3 132.0000    b       St.Johns Wood        True  NaN
876              FINE12 132.0000    n     Finsbury Market        True  NaN
889     DEPT11 BB3_2(3) 132.0000    n       Deptford Grid        True  NaN
915     NEWC11 M BB1(3) 132.0000    n     New Cross 132kV        True  NaN
926          Cub_3.0(2) 132.0000    n   Brunswick Wharf B        True  NaN
943       1026 BACA1T2A 132.0000    n           Back Hill        True  NaN
956              STEN12 132.0000    n            LPN 0035        True  NaN
965     NEWC11 R BB1(1) 132.0000    n     New Cross 132kV        True  NaN
966                T_69 132.0000    n       Wimbledon 3&4        True  NaN
972     HASC11 M BB1(3) 132.0000    n   Hackney Supergrid        True  NaN
980     ELTH11 M BB2(6) 132.0000    n         Eltham Grid        True  NaN
1003          EBBR13(1) 132.0000    n        Ebury Bridge        True  NaN
1017   SJWB11 R BB4(15) 132.0000    n       St.Johns Wood        True  NaN
1034        Terminal(8) 132.0000    n       Wimbledon 1&2        True  NaN
1039        LPN 0030(3) 132.0000    n            LPN 0030        True  NaN
1044    SJOW11 R BB1(5) 132.0000    n       St.Johns Wood        True  NaN
1045          BENW12(6) 132.0000    n       Bengeworth Rd        True  NaN
1049    SJWB11 M BB4(5) 132.0000    n       St.Johns Wood        True  NaN
1054    BARK11 R BB5(2) 132.0000    b         Barking GIS        True  NaN
1096    HASC11 R BB1(2) 132.0000    n   Hackney Supergrid        True  NaN
1100             DUST13 132.0000    n           Duke St B        True  NaN
1112    BANF11 M BB2(2) 132.0000    n            Bankside        True  NaN
1113       LPN 0034(10) 132.0000    n            LPN 0034        True  NaN
1124    BRWB11 M BB1(4) 132.0000    n   Brunswick Wharf B        True  NaN
1140    LITB11 R BB3(3) 132.0000    n         Littlebrook        True  NaN
1141    BRWB11 M BB2(7) 132.0000    n   Brunswick Wharf B        True  NaN
1154         Cub_0.0(3) 132.0000    n       Wimbledon 1&2        True  NaN
1170          MORT11(1) 132.0000    n      Moreton Street        True  NaN
1184             WISB1A 132.0000    n            LPN 0041        True  NaN
1187    WHAG11 F BB1(7) 132.0000    n            West Ham        True  NaN
1193   WHAG11 F BB1(13) 132.0000    n            West Ham        True  NaN
1200    OSBS11 R BB1(5) 132.0000    n           Osborn St        True  NaN
1210        Terminal(8) 132.0000    n            Bankside        True  NaN
1223             SIMP12 132.0000    n       Simpsons Road        True  NaN
1225        Terminal(8) 132.0000    n         Barking GIS        True  NaN
1242          TOOS12(1) 132.0000    n           Tooley St        True  NaN
1267    BARK11 R BB5(4) 132.0000    n         Barking GIS        True  NaN
1268               T_99 132.0000    n       Wimbledon 1&2        True  NaN
1278               T_72 132.0000    n    Willesden 132 kV        True  NaN
1282             FINF11 132.0000    n     Finsbury Market        True  NaN
1284       HASC11 R BB1 132.0000    b   Hackney Supergrid        True  NaN
1294             HOLL1D 132.0000    n            Holloway        True  NaN
1336    CITY11 M BB3(4) 132.0000    b           City Road        True  NaN
1342            T_23(6) 132.0000    n       St.Johns Wood        True  NaN
1343             GEST12 132.0000    n        Georgiana St        True  NaN
1370       SJOW12 M BB1 132.0000    b       St.Johns Wood        True  NaN
1398             BEEB11 132.0000    n            Beech St        True  NaN
1405    SJWB11 M BB4(1) 132.0000    n       St.Johns Wood        True  NaN
1415      8032 BACH1TP9 132.0000    b           Back Hill        True  NaN
1425         Cub_0.0(5) 132.0000    n       Wimbledon 1&2        True  NaN
1426    SJWB12 M BB3(4) 132.0000    n       St.Johns Wood        True  NaN
1440             WIMC11 132.0000    b       Wimbledon 3&4        True  NaN
1447    BRWB11 M BB2(5) 132.0000    n   Brunswick Wharf B        True  NaN
1451    SJOW11 R BB2(1) 132.0000    n       St.Johns Wood        True  NaN
1473        Terminal(8) 132.0000    n           City Road        True  NaN
1501                T_8 132.0000    n   Brunswick Wharf B        True  NaN
1507   ELTH11 M BB2(10) 132.0000    n         Eltham Grid        True  NaN
1520    SJWB11 R BB5(4) 132.0000    n       St.Johns Wood        True  NaN
1524    WIMB12 M BB4(5) 132.0000    n       Wimbledon 3&4        True  NaN
1525       NEWC11 R BB1 132.0000    b     New Cross 132kV        True  NaN
1535        Terminal(2) 132.0000    n            Bankside        True  NaN
1543        Terminal(2) 132.0000    n           Osborn St        True  NaN
1556          BENW12(5) 132.0000    n       Bengeworth Rd        True  NaN
1558          BENW12(1) 132.0000    b       Bengeworth Rd        True  NaN
1582          LIMA11(3) 132.0000    n       Limeburner LN        True  NaN
1583    SJWB11 R BB4(8) 132.0000    n       St.Johns Wood        True  NaN
1594       Terminal(26) 132.0000    n            Bankside        True  NaN
1610             LIMA1C 132.0000    n       Limeburner LN        True  NaN
1612       WIML12 R BB3 132.0000    b       Wimbledon 1&2        True  NaN
1635       BOWN11 M BB1 132.0000    b                 Bow        True  NaN
1643       BRWB11 M BB1 132.0000    b   Brunswick Wharf B        True  NaN
1648    BOWN11 R BB2(1) 132.0000    n                 Bow        True  NaN
1679      SYDP11 MC2(3) 132.0000    n       Sydenham Park        True  NaN
1680       SJOW12 M BB2 132.0000    b       St.Johns Wood        True  NaN
1691                T_7 132.0000    n     New Cross 132kV        True  NaN
1699          OBRD12(1) 132.0000    n     Old Brompton Rd        True  NaN
1700    CITY11 M BB1(6) 132.0000    n           City Road        True  NaN
1701    WHAG12 R BB1(8) 132.0000    n            West Ham        True  NaN
1717    WIML11 M BB2(1) 132.0000    n       Wimbledon 1&2        True  NaN
1750        LPN 0038(2) 132.0000    n            LPN 0038        True  NaN
1774      SYDP11 MC4(3) 132.0000    n       Sydenham Park        True  NaN
1795   WHAG12 R BB2(10) 132.0000    n            West Ham        True  NaN
1801            T_54(1) 132.0000    n       St.Johns Wood        True  NaN
1805   CITY11 M BB2(10) 132.0000    n           City Road        True  NaN
1843   CITY11 M BB2(11) 132.0000    n           City Road        True  NaN
1845         Term_LIKP1 132.0000    n         Littlebrook        True  NaN
1860            Cub_3.0 132.0000    n   Brunswick Wharf B        True  NaN
1861    HASC11 R BB2(3) 132.0000    n   Hackney Supergrid        True  NaN
1865    HASC11 M BB1(6) 132.0000    n   Hackney Supergrid        True  NaN
1878       ISLG11 R BB2 132.0000    b           Islington        True  NaN
1888             SJOW10 132.0000    n       St.Johns Wood        True  NaN
1922    OSBS11 R BB1(3) 132.0000    n           Osborn St        True  NaN
1928               T_98 132.0000    n       Wimbledon 1&2        True  NaN
1933             FISH11 132.0000    n           Fisher St        True  NaN
1938               T_79 132.0000    n    Willesden 132 kV        True  NaN
1946    WISD12 R BB2(2) 132.0000    n    Willesden 132 kV        True  NaN
1958    WISD12 R BB1(6) 132.0000    n    Willesden 132 kV        True  NaN
1972    WHAG11 F BB1(5) 132.0000    n            West Ham        True  NaN
1985            Cub_1.6 132.0000    n       Wimbledon 1&2        True  NaN
1989           T_108(2) 132.0000    n       Wimbledon 1&2        True  NaN
2009             WIMC13 132.0000    b       Wimbledon 3&4        True  NaN
2031              T_105 132.0000    n       Wimbledon 1&2        True  NaN
2036       WIMB12 M BB3 132.0000    b       Wimbledon 3&4        True  NaN
2040    WIML11 M BB2(3) 132.0000    n       Wimbledon 1&2        True  NaN
2046    SJWB11 R BB4(3) 132.0000    n       St.Johns Wood        True  NaN
2054       SJWB11 M BB5 132.0000    b       St.Johns Wood        True  NaN
2056    DEPT11 BB3_1(1) 132.0000    n       Deptford Grid        True  NaN
2058    BRWB11 R BB1(2) 132.0000    b   Brunswick Wharf B        True  NaN
2060           LPN 0045 132.0000    b            LPN 0045        True  NaN
2086           T_23(19) 132.0000    n         Littlebrook        True  NaN
2093    ELTH11 M BB2(8) 132.0000    n         Eltham Grid        True  NaN
2097    HASC11 R BB2(4) 132.0000    n   Hackney Supergrid        True  NaN
2099          BARK10(2) 132.0000    b         Barking GIS        True  NaN
2105    SJOW12 M BB1(3) 132.0000    n       St.Johns Wood        True  NaN
2137       ELTH11 M BB1 132.0000    b         Eltham Grid        True  NaN
2148    CITY11 M BB3(3) 132.0000    b           City Road        True  NaN
2153       WHAG11 F BB2 132.0000    b            West Ham        True  NaN
2156       CITY11 M BB1 132.0000    b           City Road        True  NaN
2173             LONG1A 132.0000    b       Longford St B        True  NaN
2186          DART11(1) 132.0000    b       Dartford Grid        True  NaN
2201    WISD11 M BB2(9) 132.0000    n    Willesden 132 kV        True  NaN
2219          BENW12(3) 132.0000    n       Bengeworth Rd        True  NaN
2225   WHAG11 F BB1(10) 132.0000    n            West Ham        True  NaN
2232       8010 FULC1T1 132.0000    n  Fulham Palace Rd C        True  NaN
2240    SJOW11 R BB1(3) 132.0000    n       St.Johns Wood        True  NaN
2246             WDLN11 132.0000    n           Wood Lane        True  NaN
2247    NEWC11 M BB2(5) 132.0000    n     New Cross 132kV        True  NaN
2253    BRWB11 R BB2(3) 132.0000    n   Brunswick Wharf B        True  NaN
2254             WFCS14 132.0000    n   West Ferry Circus        True  NaN
2263    NEWC11 R BB1(4) 132.0000    n     New Cross 132kV        True  NaN
2275            T_16(1) 132.0000    n                 Bow        True  NaN
2284          ABPA13(1) 132.0000    n      Aberdeen Place        True  NaN
2287        Terminal(3) 132.0000    n           Osborn St        True  NaN
2302    NEWC11 M BB1(1) 132.0000    n     New Cross 132kV        True  NaN
2315          BENW11(6) 132.0000    n       Bengeworth Rd        True  NaN
2331      3432 BRUW1TP4 132.0000    b   Brunswick Wharf B        True  NaN
2334   CITY11 M BB2(13) 132.0000    n           City Road        True  NaN
2335          OBRD11(1) 132.0000    n     Old Brompton Rd        True  NaN
2343             DART14 132.0000    b       Dartford Grid        True  NaN
2347       Terminal(34) 132.0000    n           Islington        True  NaN
2361             ELTH1J 132.0000    b         Eltham Grid        True  NaN
2367      SYDP11 MC4(1) 132.0000    b       Sydenham Park        True  NaN
2394    WHAG12 R BB1(5) 132.0000    n            West Ham        True  NaN
2397       Terminal(16) 132.0000    n           City Road        True  NaN
2400             OBRD13 132.0000    n     Old Brompton Rd        True  NaN
2413             WAND13 132.0000    n          Wandsworth        True  NaN
2422       BRWB11 R BB1 132.0000    b   Brunswick Wharf B        True  NaN
2482               1(3) 132.0000    n           Tooley St        True  NaN
2517               T_72 132.0000    n       Wimbledon 3&4        True  NaN
2536        LPN 0045(1) 132.0000    n            LPN 0045        True  NaN
2546       OSBS11 R BB2 132.0000    b           Osborn St        True  NaN
2553    OSBS11 M BB1(2) 132.0000    n           Osborn St        True  NaN
2562    ELTH12 R BB2(3) 132.0000    b         Eltham Grid        True  NaN
2563    CITY12 R BB3(2) 132.0000    n           City Road        True  NaN
2575            ND_7084 132.0000    n           Brimsdown        True  NaN
2587       Terminal(44) 132.0000    n   Hackney Supergrid        True  NaN
2592               T_54 132.0000    n           Brimsdown        True  NaN
2598    BRWB11 R BB2(4) 132.0000    b   Brunswick Wharf B        True  NaN
2603          WELT10(1) 132.0000    b            LPN 0025        True  NaN
2604       Terminal(27) 132.0000    n           Islington        True  NaN
2620    BOWN11 M BB1(3) 132.0000    n                 Bow        True  NaN
2621    OSBS11 M BB1(1) 132.0000    n           Osborn St        True  NaN
2642             HACK1C 132.0000    b   Hackney Supergrid        True  NaN
2643               T_19 132.0000    n            West Ham        True  NaN
2654          BENW11(3) 132.0000    n       Bengeworth Rd        True  NaN
2657       Terminal(23) 132.0000    b         Barking GIS        True  NaN
2661   BRWB11 M BB2(10) 132.0000    n   Brunswick Wharf B        True  NaN
2669    LITB11 M BB4(3) 132.0000    n         Littlebrook        True  NaN
2688             ABPA11 132.0000    n      Aberdeen Place        True  NaN
2708    WHAG11 F BB2(9) 132.0000    n            West Ham        True  NaN
2718    SJWB11 M BB4(4) 132.0000    n       St.Johns Wood        True  NaN
2724    OSBS11 R BB1(2) 132.0000    n           Osborn St        True  NaN
2725          LIMA13(1) 132.0000    n       Limeburner LN        True  NaN
2734               T_31 132.0000    n           City Road        True  NaN
2738    ELTH12 R BB1(4) 132.0000    n         Eltham Grid        True  NaN
2739   SJWB11 R BB4(12) 132.0000    n       St.Johns Wood        True  NaN
2746    CITY11 M BB1(4) 132.0000    n           City Road        True  NaN
2747    CITY11 M BB3(1) 132.0000    b           City Road        True  NaN
2750    CITY12 R BB2(4) 132.0000    n           City Road        True  NaN
2751    ISLG11 R BB2(7) 132.0000    n           Islington        True  NaN
2752            ND_6570 132.0000    b           Brimsdown        True  NaN
2754             FINF12 132.0000    n     Finsbury Market        True  NaN
2763               T_43 132.0000    n           City Road        True  NaN
2779      1420 SJOW1TP7 132.0000    n       St.Johns Wood        True  NaN
2780   BRWB11 M BB1(10) 132.0000    n   Brunswick Wharf B        True  NaN

In [214]:
print("now the HV lines")
net.line['vn_kv_bus'] = net.line.from_bus.map(net.bus.vn_kv)
print(net.line.loc[(net.line.vn_kv_bus > 100) & (net.line.vn_kv_bus < 150)])

now the HV lines
                                   name std_type  from_bus  to_bus  length_km  \
0                       lne_BRWB_WFCS_1     None      6160    7589     2.1750
3                       lne_NEWC_TOOL_1     None     10443    9394     4.4000
6                       lne_WISD_FULC_1     None      4538    2232    12.1200
11                      lne_WM12_BENG_2     None      1045    3982     9.1400
15                      Lne_BANF_FISB_3     None      6060    9578     3.0000
18                      lne_LITB_DART_3     None     10535    2343     3.7600
20                    lne_ELTH_ELTM_T1B     None      8760    4450     1.0000
32                      lne_HURS_BROM_1     None      9043      54     1.0000
35                     lne_ISLNG_GEORG1     None      6661    3988     2.8000
42                      lne_CITY_CITB_2     None      3821    2912     1.0000
45                       L_BANK_BANDGT5     None      6067    2815     1.0000
47                           lne_SJOW_2     None      4062    2105     0.2600
49                      lne_CITY_FINM_2     None      5245     876     1.0000
55                    lne_ELTH_ELTG_T1A     None      7785    8413     1.0000
57                       lne_OBRD_GRID1     None      2335    5692     1.0000
58                           Lne_HURS_3     None        58    9088     1.0000
60                      lne_BRIM_EECB_1     None      2575    2752     0.2000
65                      lne_BRWB_OSCL_1     None      1124    4627     2.2000
66                      lne_LEIR_GRID1B     None      7507     447     1.0000
68                      lne_ISLNG_HOOW1     None      9501    3105     0.3500
69                      lne_OSBS_OSBB_2     None      9381    4320     0.0730
74                          LPN 0006(5)     None       284    7102     0.4500
75                      lne_CITY_HOXT_1     None      9151    6107     1.7500
76                      lne_WELT_DART_1     None      4103    6921     0.6000
81                        lne_WHAM_CORA     None      8504    1113     1.7746
82                             LPN 0004     None      5045    8778     5.8000
86                      lne_BOWM_BOWT_2     None      9580    8850     2.0000
90                      lne_CITY_FINM_1     None      7073    3213     1.0000
95                 lne_BANF_CITY_LIMA_2     None      1582    2889     0.1000
96                 lne_SJOW_DUST/LESQ_1     None       152    2942     2.9000
104                     lne_CITY_BEEB_1     None       119    3960     2.1900
108                   lne_WHSG_WH11_T1B     None      4708    3055     1.0000
110                     lne_WM12_KITO_2     None      7915    4294     1.0000
112                     lne_BRIM_BUCK_1     None     10371    3003     1.0000
120                     lne_LITB_DART_2     None      7027    8650     3.6600
123                   lne_WHSG_WH11_T2B     None      7818    5722     1.0000
129                     lne_CITR_CITC_3     None      5588    2334     1.0000
133                     lne_LEIR_GIBR_1     None      7507    9561     1.0000
137                     lne_NEWC_CANJ_1     None      4424    5925     1.3500
144                     lne_LONG_BACH_1     None      5887    2173     1.0000
145                lne_TAYT_GIBR/LEIR_3     None      3039    5638     1.0000
153                     lne_BOWM_BWNR_4     None      2620    4507     1.0000
154                      lne_CITY_DEVO2     None     10052    9094     2.8560
159                     lne_BARK_BARG_1     None      1267    5849     0.8580
160                     lne_WHAM_BRUW_1     None      2394    4615     1.3936
166                   lne_HOOW_HOLW_T2A     None      1294    6321     1.0000
175                     lne_OBRD_EBBR_2     None      7325   10555     4.6100
182                     lne_SJWB_OBRD_1     None      4200    5692     0.1600
188                lne_WM34_WIMC_GRID4B     None       755    5278     1.0000
191                   lne_HACK/KGYB_GT1     None       972    5713     1.0000
192                      lne_LONG_GRID1     None      9001    2173     1.0000
193                     Lne_CITY_LIMA_2     None      2987     488     2.6560
195                     lne_BOWM_BOWT_1     None      6618    6502     2.0000
198                lne_WM34_WIMC_GRID2B     None      8333    8250     1.0000
202                        lne_R2_SECT1     None      1154    5650     0.0710
203                     lne_BANF_TOOL_1     None      4995    8879     1.5000
207         lne_SJOW_OBRD/EBRY2/SJWDT3B     None      4706    4400     1.0000
209                lne_SJOW_DUST/LESQ_3     None      1100    5400     2.9000
211                   Lne_BANF_BANC_GT2     None      9985    4996     1.0000
213                lne_WISD_WISB_GRID1B     None      6862    8391     1.0000
215                      lne_CITY_DEVO1     None      5766    4871     2.8560
218                    lne_BOW_KGYA_GT2     None     10128    3093     1.0000
222                        lne_R1_SECT1     None      1425    4441     0.1030
223                        lne_R1_SECT2     None      9123    1034     0.1030
237                       lne_ELTH_RES1     None      9759    6084     0.0100
241                         LPN 0030(1)     None     10347    1039     1.2000
244                     lne_CITR_CITC_4     None      5547    9964     1.0000
247                            LPN 0038     None      6153    1750     1.6000
248                lne_FINM_FINC_GRID1C     None      6843    1282     1.0000
252                         LPN 0045(7)     None      2060    2040     1.0000
253                      lne_LONG_GRID3     None      3021    7841     1.0000
255                     lne_OSBS_OSBB_1     None      3601    9365     1.0000
256                            LPN 0011     None      8129     201     1.4000
268                lne_WISD_GIBR/LEIR_1     None      5134    7507     1.7700
278                     lne_ELTH_SYDK_2     None       244    8267    13.3800
279                    lne_BEDD__SYDK_2     None      9019     576     1.0000
287                       lne_INTER 4-1     None       749    2739     0.2600
295                      lne_TOOL_GRID2     None      8465    4077     1.0000
298                     lne_HACK_GRID1B     None      1865    9949     1.0000
308                     lne_SJOW_SJWD3B     None      8304    8075     1.0000
310                   lne_WHSG_STEN_T3D     None      9438    9200     1.0000
312                     lne_ISLNG_HOOW2     None      4972     805     0.3700
315                     lne_ELTH_SYDK_1     None      9256    4756    13.3400
316                     lne_WHSG_WFCS_1     None      2225    8120     3.5200
317                   lne_ELTH_ELTM_T4B     None      2093    8272     1.0000
321                     lne_WISD_FULC_2     None      7125    4681    12.1600
322                     lne_SJOW_ABPB_1     None      9589    3108     1.0000
323                lne_WM34_WIMC_GRID1B     None      1440    8106     1.0000
324    lne_WHSG_WHBRT4A/WH11T4B/WHAST4C     None      3958    7424     1.0000
328                     lne_NEWC_OSBS_1     None       105    4128     4.7250
332                     lne_NEWC_OSBS_3     None      8771    8740     4.7250
334                     lne_WM12_KITO_1     None        78    1985     1.0000
338                lne_TAYT_GIBR/LEIR_2     None      1750    4741     1.0000
341                     lne_HURS_ELTH_2     None      6797    9088     1.0000
346                     Lne_WAND_MORT_1     None      3723   10445     6.0000
349                     lne_LEIR_GIBR_3     None      5638    8603     1.0000
353                          Cable_S603     None     10735    3175     0.1650
361                     lne_SJOW_OBRD_3     None      8311    8075     6.2100
373                     lne_WELT_DART_4     None      7769    9213     0.5800
374                     lne_SJWB_AMBL_1     None      9347    8654     2.5000
377                       lne_ELTH_RES2     None      7814    2562     0.0100
378                     lne_SJOW_ABPB_5     None      9537    5424     1.0000
380                     lne_NEWC_TOOL_2     None      8178    1242     4.4000
381                     lne_WHSG_BOWM_1     None      9240    7533     1.0000
389                     lne_NEWC_DEPT_1     None      5836   10058     2.9930
405                     lne_WM34_LOTS_1     None      3517    3510     1.0000
406                     lne_BARK_BARG_4     None      7552    6154     0.8340
409                     lne_CITY_BACH_1     None      3879    5909     1.0000
414                     Lne_WHAM_BRUW_4     None       141    8753     1.5500
417                     lne_BRUW_SIMP_1     None      7475    2888     1.6300
422                     Lne_LIMA_BANF_1     None       845    6943     1.5000
424                    lne_BEDD__SYDK_1     None       187    5980     1.0000
425                     lne_WISD_WDLN_2     None      4675    2246     4.0450
428                   Lne_BANF_BANC_GT4     None      9242    4040     1.0000
431                     lne_CITY_FINM_3     None      4135    9893     1.0000
434                      lne_WM34_STEW2     None      8162    8708     8.5400
437                     lne_CITY_BEEB_2     None      1398    2397     1.0000
438                lne_SJOW_DUST/LESQ_2     None      7771    6830     2.9000
439                lne_BANF_CITY_LIMA_3     None      7076    8835     0.1000
445                         LPN 0011(1)     None      9192   10668     1.4000
451                lne_WM34_WIMC_GRID3B     None      2009    1524     1.0000
465                     lne_WISD_FULC_3     None      5589     567     1.0000
466                     lne_BRUW_SIMP_2     None      1223    6604     1.7200
469                     lne_SJOW_ABPA_8     None      5018    8555     1.0000
473           lne_FINM_FINA/FINB/FINC_1     None      3213    3286     1.0000
476                     Lne_CITY_LIMA_1     None      5003    2725     2.6560
478                     lne_HURS_BROM_2     None      7910   10304     1.0000
483                      lne_LONG_GRID2     None      4179    9113     1.0000
485                     lne_FISH_BANF_2     None      1594    8683     3.0000
489                     lne_BRWB_OSCL_2     None      5492    7728     2.2000
491                     lne_HACK_GRID1A     None       137    2642     1.0000
493                     lne_HURS_ELTH_1     None      6797    9088     1.0000
496                          lne_SJOW_1     None      5312    2240     0.2600
508                     lne_SJOW_LONG_3     None      7841    5279     1.0000
509                   lne_SJOW_SJWD_T5B     None      2779    9562     1.0000
514                    lne_SJOW_SJWD_3B     None      1520    7313     0.1000
517                        lne_R2_SECT2     None     10551    6928     0.0710
523                         LPN 0038(1)     None      7721    3039     1.6000
528                     lne_SJOW_ABPA_6     None      8926    9954     0.5000
530                      lne_TOOL_GRID1     None      8398    4818     1.0000
532                      lne_OBRD_GRID2     None      1699   10555     1.0000
537                     lne_BRUW_LLCR_2     None      1447    4669     0.7480
538                     lne_BENW_DEPT_1     None      9520    2056     6.6700
540                     lne_WM34_WANS_4     None     10407   10511     1.0000
544                     lne_BARK_BARG_3     None     10161    4517     0.8790
546                      lne_CITY_DEVO3     None      8011    1473     2.8560
548                lne_WISD_WILB_GRID2A     None      5257    5137     1.0000
565                                C707     None      5105    4951     9.3800
567                     lne_SJOW_LONG_1     None      2173    8705     1.0000
573                     lne_CITY_BEEB_3     None      3899    7415     1.0000
575                     lne_OBRD_EBBR_3     None      1003    8311     4.6300
580                            LPN 0030     None      4717    5091     1.0000
583                     lne_HACK_GRID2B     None      6056    1861     1.0000
585                     lne_SJOW_ABPA_2     None      2284    3652     1.0000
586                     Lne_WAND_MORT_2     None      5483    3222     6.0000
596    lne_WHSG_WHBRT3A/WH11T3B/WHAST3C     None      1193    6437     1.0000
601                     lne_BOWM_BWNR_5     None      3479    1648     1.0000
602                     lne_LONG_BACH_3     None      7841    3525     1.0000
603                   lne_WHSG_STEN_T4D     None       956    2708     1.0000
617                     lne_NEWC_DEPT_2     None      9141    2247     2.9930
619                     Lne_LIMA_BANF_2     None      5825    1535     1.5000
621                     lne_SJOW_OBRD_2     None     10555    4400     6.2600
623                     Lne_CITY_LIMA_3     None      6465     493     2.6560
624                           EX_HOLL_1     None      3188    5150    13.1800
629                      lne_WM34_WANS1     None      2413    5077     1.0000
636         lne_WISD_GRID1B/WILB_GRID1A     None      9058    6862     1.0000
641                Lne_BANF_CITY_LIMA_1     None      3147    1610     0.1000
642                     lne_LEIR_GRID3B     None      7394    5638     1.0000
644                lne_WISD_WILB_GRID1A     None      6862    3330     1.0000
647                     lne_WISD_NPBR_3     None       402     439     1.0000
648                     lne_WM12_BENG_1     None      2315    1717     1.0000
652                     lne_BRUW_SIMP_3     None      7951    7863     1.5900
655                     lne_LITT_WELD_4     None      2669    7769     3.1000
656                     lne_ISLG1_SJOW1     None      5059    6157     4.4160
661                     lne_VISC_MORT_1     None       819    3222     1.1060
663                   lne_HOOW_HOLL_T1B     None      6497     104     1.0000
668                      lne_OBRD_GRID3     None      3744    8311     1.0000
671                   Lne_BANF_BANC_GT3     None      1210    6316     1.0000
676                     lne_NEWC_OSBS_2     None      8742    1200     4.7250
678                     lne_ELTH_BROM_1     None      4805    5188     1.0000
679                    lne_WIMB34_STEW1     None      9267    3764     8.5400
681                     lne_SJOW_ABPA_4     None      5528    1017     0.5000
682                     lne_BRIM_BUCK_2     None      8232    3707     1.0000
684                   lne_HOOW_HOLW_T1A     None       394    7760     1.0000
696                     Lne_CITY_CALS_2     None       195   10668     2.4800
697                     lne_BRWB_BKWY_2     None      9871    2865     0.5000
701                     lne_DUST_LESQ_1     None       152    7312     2.4700
708                     lne_BENW_LAND_2     None      5944    6050     4.9000
710                          Cable_S605     None     10745    4129     0.1700
714                    lne_ISLNG_GEORG2     None      7700    1343     2.8000
716                     lne_DUST_LESQ_3     None      1100    4063     2.4700
720                lne_FINM_FINC_GRID2C     None      2962    2754     1.0000
721                       lne_BRWB_CORA     None      3852     926     0.7400
723                     lne_WISD_WDLN_1     None      7908    5800     4.0450
724                     lne_SJWB_AMBL_2     None      3403    6006     2.5000
726                   lne_ELTH_ELTM_T2B     None      1507    5298     1.0000
730                lne_FINM_FINC_GRID3C     None      3682    4520     1.0000
731                      lne_CITY_MANS2     None       480    6606     1.0000
734                          lne_ELTH_1     None      8049    6797     1.0000
741                     lne_LONG_BACH_2     None      7901    9113     1.0000
742                     lne_BANF_TOOL_2     None      9528    3379     1.5000
743                     lne_FISH_BANF_1     None      3977    1933     3.0000
744                     lne_BRUW_LLCR_1     None      9037    5525     0.7480
747               lne_SJOW_Cap 1A 1B 1C     None      1342    3661     0.0001
749                   lne_HOOW_HOLL_T2B     None      5744    3930     1.0000
758                     lne_DUST_LESQ_2     None      7771    4876     2.4700
765                     lne_ELTH_BROM_2     None      4550    5923     1.0000
766                  Lne_BANF_BANC_GT1A     None      9087    9934     1.0000
768         lne_WISD_GRID2B/WILB_GRID2A     None       538    5257     1.0000
769                     lne_VISC_MORT_2     None     10084   10445     1.1060
771           lne_FINM_FINA/FINB/FINC_2     None       876    3066     1.0000
774                     lne_LITB_WELD_1     None      4103    1140     3.1500
775                    lne_BOW_KGYA_GT3     None      3923    6775     1.0000
778                     lne_NEWC_CANJ_2     None       556    9492     1.3500
786                   lne_DEPT_DEPD_T4B     None      7837     465     1.0000
789                     lne_LEIR_GRID2B     None      4741    4180     0.2000
792                     lne_BRWB_BKWY_1     None      4457   10633     0.5000
793                     lne_HACK_GRID2A     None      9437    5777     1.0000
797                     lne_CITY_BACH_3     None      2916    1415     1.0000
799                   Fut_lne_INTER 4-1     None       736   10617     0.2600
800                     lne_CITY_MANS_1     None      6238    9318     4.2500
804                     Lne_CITY_CALS_1     None      3113     201     2.4800
806                   lne_ELTH_ELTG_T2A     None      9585    5082     1.0000
807           FUTE_lne_LITB_LIKP1/NFLE4     None       255    9063     3.7600
825                     lne_WHSG_BOWM_2     None      1795    8574     1.0000
836           FUTE_lne_LITB_LIKP2/NFLE3     None      5839     144     3.7600
838                     lne_OSBS_OSBB_3     None      9744    6284     0.0830
841                     lne_LEIR_GIBR_2     None      4741    6767     1.0000
845                     lne_BOWM_HACG_1     None      4939    8745     4.3000
848                     lne_CALS_CALS_1     None      3552    5622     0.0950
852                       lne_HACK_BRWB     None      3918    4933     7.5150
855                          Cable_S604     None     10714    4567     0.1700
857  lne_SJOW_OBRD/EBRY1/ABPBT5/SJWDT5B     None      1888    9562     1.0000
862                     lne_DEPT_LAND_2     None      5217    7466     1.8000
866                     lne_OBRD_EBBR_1     None      7839    5692     4.6300
868                     lne_CITY_CITB_1     None      8174    1843     1.0000
869                     lne_SJOW_LONG_2     None      9113     300     1.0000
872           lne_FINM_FINA/FINB/FINC_3     None      9893    3181     1.0000
878                     Lne_LIMA_BANF_3     None      2959      76     1.5000
881                                C706     None      7168    3560     9.3450
886                     lne_WHSG_WFCS_2     None      6020    4465     3.5200
892                     lne_BARK_BARG_2     None       644    6403     0.8340
896                   lne_ELTH_ELTG_T4A     None      7534    2361     1.0000
898                    lne_ISLNG_GEORG3     None      7687    3512     2.8000
899                lne_WISD_WISB_GRID2B     None      5257    1184     1.0000
905                     lne_BOWM_HACG_2     None      7712    9165     4.3000
906                     Lne_WHAM_BRUW_3     None      5123    4380     1.5500
913                     lne_CALS_CALS_2     None       442    5509     0.0950
916                     L_BANF_BANDGT1B     None       306     693     1.0000
917                     lne_WM34_LOTS_2     None      8175    5389     1.0000
919                     lne_CITY_BACH_2     None      4088   10075     1.0000
931                    lne_SJWB_SJWD_5B     None      3554    9131     0.1600
932                            LPN 0045     None      3049    2536     0.1780
933                     lne_WM34_WANS_2     None      7252    6983     1.0000
934                     lne_WM34_WANS_3     None      5801    6239     1.0000

In [215]:
print("now the HV 2W trafos")
print(net.trafo.loc[(net.trafo.vn_hv_kv > 100) & (net.trafo.vn_hv_kv < 150)])

now the HV 2W trafos
            name std_type  hv_bus  lv_bus   sn_mva  vn_hv_kv  vn_lv_kv  \
1            GT1     None    5102    8079  60.0000  132.0000   33.0000
4            GT3     None   10409     929  60.0000  132.0000   22.0000
8        T1_EECL     None    2752     715 520.0000  132.0000   22.0000
15          GT1C     None    1282    6043  90.0000  132.0000   33.0000
19          GT4B     None    2186    6044  15.0000  132.0000   11.0000
21          GT1A     None   10439    6381  15.0000  132.0000   11.0000
26          GT2B     None    8333    8571  90.0000  132.0000   33.0000
44          GT2A     None    7194    4217  15.0000  132.0000   11.0000
51          GT1A     None    9854    5467  15.0000  132.0000   11.0000
58           GT1     None    6107    1722  60.0000  132.0000   33.0000
59          GT3B     None    6883    9395  15.0000  132.0000   11.0000
62          GT2B     None    7252    6358  90.0000  132.0000   66.0000
63   LPN 0045(3)     None    2536    1298  90.0000  132.0000   33.0000
70           GT1     None    5849    5869  30.0000  132.0000   66.0000
71          GT3B     None    2009    9018  90.0000  132.0000   33.0000
72   LPN 0043(2)     None    9199    7401  40.0000  132.0000   11.0000
73          GT3B     None    5801      94  90.0000  132.0000   66.0000
74          GT4B     None     755    3624  90.0000  132.0000   33.0000
78          GT1B     None    2413    7178  90.0000  132.0000   66.0000
80           GT1     None    8398    4138  36.0000  132.0000   11.0000
86          GT2B     None    1679    9801  45.0000  132.0000   33.0000
87          GT1A     None    3410   10020  60.0000  132.0000   33.0000
90          GT3B     None    7313    3436  45.0000  132.0000   22.0000
96          GT1B     None     447    5890  60.0000  132.0000   33.0000
100         GT3A     None   10132    9245  15.0000  132.0000   11.0000
101         GT1B     None    9949    2605  60.0000  132.0000   66.0000
106         GT1B     None    4450    5025  15.0000  132.0000   11.0000
107         GT4A     None    2367    8617  15.0000  132.0000   11.0000
108          GT3     None    5750      60  45.0000  132.0000   33.0000
109         GT4C     None    8400    2151  90.0000  132.0000   66.0000
115         GT4B     None    1774    9659  45.0000  132.0000   33.0000
120         GT3A     None    4520    8747  15.0000  132.0000   11.0000
127         GT4A     None     446    8862  30.0000  132.0000   11.0000
133         GT3B     None    5075    4315  45.0000  132.0000   33.0000
145          GT3     None     386    7387  90.0000  132.0000   33.0000
146  LPN 0067(4)     None    4669    1673  32.0000  132.0000   22.0000
148         GT2B     None    6583    4162  15.0000  132.0000   11.0000
152          GT1     None    5800    2971  33.3000  132.0000   11.1100
155  LPN 0036(2)     None    9615   10362  26.5000  132.0000   25.0000
156  LPN 0022(2)     None    4507    1649  85.0000  132.0000   25.0000
157  LPN 0067(3)     None    5525    7870  32.0000  132.0000   22.0000
158         GT4B     None    6518     765  45.0000  132.0000   33.0000
161          GT2     None    9665    1657  15.0000  132.0000   11.0000
164          T1B     None    6497    3001  60.0000  132.0000   66.0000
171         GT3B     None    3139    3842  45.0000  132.0000   33.0000
173         GT1A     None    6843    5955  15.0000  132.0000   11.0000
174         GT2A     None    7883    7408  60.0000  132.0000   33.0000
175          GT3     None    4517    1552  30.0000  132.0000   66.0000
178          GT1     None    7519    7912  90.0000  132.0000   33.0000
180  LPN 0022(3)     None    3479    7379  85.0000  132.0000   25.0000
185         GT1B     None    8899     857  45.0000  132.0000   33.0000
193         GT1B     None    8324    1459  15.0000  132.0000   11.0000
196          GT2     None    8465    2282  36.0000  132.0000   11.0000
200  LPN 0025(3)     None    2603    3781  30.0000  132.0000   11.0000
202  LPN 0041(3)     None    3330    1664  20.0000  132.0000   11.0000
204         GT3C     None    6033     303  90.0000  132.0000   66.0000
210         GT3B     None    8567    5024  45.0000  132.0000   33.0000
219         GT2B     None    3023     500  45.0000  132.0000   33.0000
222         GT2B     None    4180    4390  60.0000  132.0000   33.0000
228  LPN 0026(3)     None    9492    7540  60.0000  132.0000   33.0000
237         GT1A     None    9784    8289  45.0000  132.0000   33.0000
242          GT4     None    1556    1585  45.0000  132.0000   33.0000
246          GT2     None    8770    6578  60.0000  132.0000   33.0000
250         GT2B     None    5298    2883  15.0000  132.0000   11.0000
251  LPN 0025(2)     None   10062    7567  30.0000  132.0000   11.0000
254          GT2     None    2246    1569  33.3000  132.0000   11.1100
258  LPN 0039(2)     None     439    8254  26.5000  132.0000   25.0000
260          GT6     None    6206    7753  15.0000  132.0000   11.0000
261         GT3B     None    7307    7353  15.0000  132.0000   11.0000
266         GT3B     None    3908    3664  30.0000  132.0000   11.0000
269         GT2A     None    9437    7734  60.0000  132.0000   66.0000
271          GT4     None    5097   10266  45.0000  132.0000   33.0000
276         GT2A     None     943    4961  15.0000  132.0000   11.0000
279          GT3     None    4126    5838  60.0000  132.0000   33.0000
286         GT4B     None    8272    2537  15.0000  132.0000   11.0000
287  LPN 0036(3)     None    7635   10008  26.5000  132.0000   25.0000
304         GT1A     None    8413    8905  45.0000  132.0000   33.0000
305          GT5     None    5424    7740  30.0000  132.0000   11.0000
310          T2B     None    5744    4962  60.0000  132.0000   66.0000
311         GT1B     None    3844    3396  45.0000  132.0000   33.0000
318         GT3A     None    7051    4308  45.0000  132.0000   33.0000
325         GT5B     None    9131    2453  45.0000  132.0000   22.0000
331         GT4A     None    6602    3905  45.0000  132.0000   33.0000
343          GT2     None    9203    9515  90.0000  132.0000   33.0000
348  LPN 0026(2)     None    5925    4086  60.0000  132.0000   33.0000
351         GT3A     None    7399    5767  15.0000  132.0000   11.0000
355          GT8     None    2688    7096  15.0000  132.0000   11.0000
357         GT4B     None    7671    9345  30.0000  132.0000   11.0000
358         GT2B     None    6056    2154  60.0000  132.0000   66.0000
361          GT1     None    6676    5510  30.0000  132.0000   11.0000
364     LPN 0040     None    8391    8993  26.5000  132.0000   25.0000
373          GT2     None    6403   10426  30.0000  132.0000   66.0000
375         GT4B     None   10407    8765  90.0000  132.0000   66.0000
377         GT1B     None    3760    5885  60.0000  132.0000   33.0000
378         GT2A     None   10333    3198  45.0000  132.0000   33.0000
380         GT2A     None    2962    8941  15.0000  132.0000   11.0000
382         GT2C     None    2754    5161  90.0000  132.0000   33.0000
384          GT2     None    2219    4107  45.0000  132.0000   33.0000
403         GT3A     None    6137    5833  45.0000  132.0000   33.0000
412  LPN 0040(1)     None    1184   10001  22.0000  132.0000   25.0000
415          GT4     None    8098    3112  15.0000  132.0000   11.0000
420          GT4     None    6154    9352  30.0000  132.0000   66.0000
426         GT1B     None   10318    9675  45.0000  132.0000   33.0000
427         GT2B     None    8683    2551  33.3000  132.0000   11.0000
429         GT1A     None    2642    4361  60.0000  132.0000   66.0000
435         GT3B     None    9578    6370  33.3000  132.0000   11.0000
436         GT1B     None    1440    7921  90.0000  132.0000   33.0000
437  LPN 0045(4)     None    2060    6959  90.0000  132.0000   33.0000
439  LPN 0041(4)     None    5137    6689  20.0000  132.0000   11.0000
444         GT2B     None    4428    4407  60.0000  132.0000   33.0000
445          GT4     None   10559    8252  60.0000  132.0000   33.0000
452         GT4A     None    2361   10274  45.0000  132.0000   33.0000
457         GT3C     None    3682   10353  90.0000  132.0000   33.0000
466          GT5     None     889    4239  45.0000  132.0000   22.0000
469         GT1B     None    1933    1660  33.3000  132.0000   11.0000
472         GT3B     None    7394    1772  60.0000  132.0000   33.0000
477          GT1     None    2654    2539  45.0000  132.0000   33.0000
482         GT2A     None    5082     752  45.0000  132.0000   33.0000

     vk_percent  vkr_percent   pfe_kw  ...  tap2_step_degree  vk0_percent  \
1       14.8400       0.5278  43.1401  ...               NaN          NaN
4       12.8400       0.6000  46.2001  ...               NaN          NaN
8       20.1509       1.0400   0.0000  ...               NaN          NaN
15      23.1800       0.4021   0.0000  ...               NaN          NaN
19      19.5200       1.2047  15.8000  ...               NaN          NaN
21      20.6000       1.0180  22.5799  ...               NaN          NaN
26      22.7500       0.6078  57.0000  ...               NaN          NaN
44      20.6000       1.1033  20.7100  ...               NaN          NaN
51      20.5500       1.1560  29.2000  ...               NaN          NaN
58      17.0000       0.4392  16.8950  ...               NaN          NaN
59      19.5200       1.2047  15.8000  ...               NaN          NaN
62      16.7500       0.5893   0.0000  ...               NaN          NaN
63      12.9304       0.6300   0.0000  ...               NaN          NaN
70      10.2000       0.6967  65.9401  ...               NaN          NaN
71      22.2900       0.3834  30.0700  ...               NaN          NaN
72      10.0125       0.5000   0.0000  ...               NaN          NaN
73      17.8000       0.5894   0.0000  ...               NaN          NaN
74      22.2900       0.3834  30.0700  ...               NaN          NaN
78      16.7000       0.5900   0.0000  ...               NaN          NaN
80      43.8700       0.7727  10.6000  ...               NaN          NaN
86      12.7500       0.6124  42.7500  ...               NaN          NaN
87      12.1500       0.5873  46.2001  ...               NaN          NaN
90      12.1400       0.6622  42.9481  ...               NaN          NaN
96      17.0200       0.4461  17.7289  ...               NaN          NaN
100     20.5500       1.1413  30.7000  ...               NaN          NaN
101     13.2000       0.5042  27.7800  ...               NaN          NaN
106     19.8600       1.2100  18.5301  ...               NaN          NaN
107     20.6000       1.0973  21.6960  ...               NaN          NaN
108     12.5010       0.6705  44.6000  ...               NaN          NaN
109     17.4000       0.7278  55.0999  ...               NaN          NaN
115     12.3400       0.6667  41.9000  ...               NaN          NaN
120     20.0000       1.1067  15.0400  ...               NaN          NaN
127     19.2001       0.8007  24.5001  ...               NaN          NaN
133     12.3600       0.5267  85.2000  ...               NaN          NaN
145     23.0800       0.3994  28.1610  ...               NaN          NaN
146     15.8700       0.5332  12.7210  ...               NaN          NaN
148     19.7500       1.2173  15.2000  ...               NaN          NaN
152     37.2401       0.4798  11.4980  ...               NaN          NaN
155     18.1500       0.7939   8.7920  ...               NaN          NaN
156     54.7799       1.4847   0.0000  ...               NaN          NaN
157     15.8300       0.5347  12.5500  ...               NaN          NaN
158     10.0200       0.5596  61.4341  ...               NaN          NaN
161     19.8300       1.0080  20.1599  ...               NaN          NaN
164     12.3000       0.5922  64.8000  ...               NaN          NaN
171     10.1000       0.5950  45.4000  ...               NaN          NaN
173     20.0000       1.1227  15.6400  ...               NaN          NaN
174     12.1000       0.5846  46.0600  ...               NaN          NaN
175     10.4400       0.8005  27.9760  ...               NaN          NaN
178     23.0800       0.3994  28.1610  ...               NaN          NaN
180     54.7799       1.4847   0.0000  ...               NaN          NaN
185     12.5600       0.6147  40.5000  ...               NaN          NaN
193     19.5200       1.2047  15.8000  ...               NaN          NaN
196     43.8700       0.7727  10.6000  ...               NaN          NaN
200     30.8769       0.6510   0.0000  ...               NaN          NaN
202     13.7100       0.9830  19.9480  ...               NaN          NaN
204     17.2000       0.7230  54.3000  ...               NaN          NaN
210     12.7500       0.6124  42.7500  ...               NaN          NaN
219     12.3500       0.5229  88.0801  ...               NaN          NaN
222     17.0400       0.4319  17.9110  ...               NaN          NaN
228     16.7700       0.4417  16.1370  ...               NaN          NaN
237     12.4300       0.6243  93.9249  ...               NaN          NaN
242     12.5008       0.6660  44.9999  ...               NaN          NaN
246     14.7700       0.5642  46.8200  ...               NaN          NaN
250     19.8600       1.2100  18.5301  ...               NaN          NaN
251     30.8769       0.6510   0.0000  ...               NaN          NaN
254     37.5801       0.4832  11.5670  ...               NaN          NaN
258     18.4301       0.7429   8.1120  ...               NaN          NaN
260     19.8000       1.0220  20.4000  ...               NaN          NaN
261     19.8600       1.2100  18.5301  ...               NaN          NaN
266     21.4411       0.9480  10.8400  ...               NaN          NaN
269     12.4000       0.5123  66.0000  ...               NaN          NaN
271     12.5496       0.5746   0.0000  ...               NaN          NaN
276     20.4500       1.1627  29.2000  ...               NaN          NaN
279     14.7700       0.5740  46.3600  ...               NaN          NaN
286     19.9000       1.2647  16.1000  ...               NaN          NaN
287     18.2500       0.7805   8.5000  ...               NaN          NaN
304     12.4500       0.5578  64.0841  ...               NaN          NaN
305     29.5001       0.6403  10.8400  ...               NaN          NaN
310     12.3000       0.5922  64.8000  ...               NaN          NaN
311     12.1800       0.4920  48.0599  ...               NaN          NaN
318     13.3600       0.4279   0.0000  ...               NaN          NaN
325     12.2400       0.6633  44.6800  ...               NaN          NaN
331     12.4500       0.6400  85.3001  ...               NaN          NaN
343     23.0300       0.4010  28.5630  ...               NaN          NaN
348     16.7700       0.4417  16.1370  ...               NaN          NaN
351     20.5200       1.1183  20.7100  ...               NaN          NaN
355     19.7600       1.0300  19.9200  ...               NaN          NaN
357     21.8200       0.9400  24.8999  ...               NaN          NaN
358     12.9000       0.6817 105.0000  ...               NaN          NaN
361     29.6000       0.6510  10.7600  ...               NaN          NaN
364     18.7863       0.9540   0.0000  ...               NaN          NaN
373     10.1709       0.7110   0.0000  ...               NaN          NaN
375     17.8000       0.5894   0.0000  ...               NaN          NaN
377     12.1000       0.5858  44.9999  ...               NaN          NaN
378     12.4300       0.6307  84.6000  ...               NaN          NaN
380     20.0000       1.1067  15.0400  ...               NaN          NaN
382     23.1700       0.3993   0.0000  ...               NaN          NaN
384     13.0182       0.5850   0.0000  ...               NaN          NaN
403     12.4200       0.6296  86.3000  ...               NaN          NaN
412     15.5973       0.8140   0.0000  ...               NaN          NaN
415     19.8500       1.0293  20.4000  ...               NaN          NaN
420     10.4300       0.8055  28.5600  ...               NaN          NaN
426     12.9000       0.5396  47.1899  ...               NaN          NaN
427     35.3799       0.4806  11.0000  ...               NaN          NaN
429     12.3000       0.5400  64.8000  ...               NaN          NaN
435     35.3799       0.4806  11.0000  ...               NaN          NaN
436     22.8000       0.6078  56.6400  ...               NaN          NaN
437     12.9304       0.6300   0.0000  ...               NaN          NaN
439     13.5100       0.9762  20.3519  ...               NaN          NaN
444     12.2400       0.5910  46.5000  ...               NaN          NaN
445     15.0000       0.5967  42.5999  ...               NaN          NaN
452     13.3600       0.4279   0.0000  ...               NaN          NaN
457     23.1000       0.4020   0.0000  ...               NaN          NaN
466     12.1500       0.6300  38.4001  ...               NaN          NaN
469     35.3799       0.4806  11.0000  ...               NaN          NaN
472     17.0400       0.4319  17.9110  ...               NaN          NaN
477     12.5000       0.5679  62.2190  ...               NaN          NaN
482     12.5800       0.5556  66.0350  ...               NaN          NaN

    vkr0_percent  xn_ohm  CurrentLimit.value_hv  CurrentLimit.value_lv  \
1            NaN     NaN                    NaN                    NaN
4            NaN     NaN                    NaN                    NaN
8            NaN     NaN                    NaN                    NaN
15           NaN     NaN                    NaN                    NaN
19           NaN     NaN                    NaN                    NaN
21           NaN     NaN                    NaN                    NaN
26           NaN     NaN                    NaN                    NaN
44           NaN     NaN                    NaN                    NaN
51           NaN     NaN                    NaN                    NaN
58           NaN     NaN                    NaN                    NaN
59           NaN     NaN                    NaN                    NaN
62           NaN     NaN                    NaN                    NaN
63           NaN     NaN                    NaN                    NaN
70           NaN     NaN                    NaN                    NaN
71           NaN     NaN                    NaN                    NaN
72           NaN     NaN                    NaN                    NaN
73           NaN     NaN                    NaN                    NaN
74           NaN     NaN                    NaN                    NaN
78           NaN     NaN                    NaN                    NaN
80           NaN     NaN                    NaN                    NaN
86           NaN     NaN                    NaN                    NaN
87           NaN     NaN                    NaN                    NaN
90           NaN     NaN                    NaN                    NaN
96           NaN     NaN                    NaN                    NaN
100          NaN     NaN                    NaN                    NaN
101          NaN     NaN                    NaN                    NaN
106          NaN     NaN                    NaN                    NaN
107          NaN     NaN                    NaN                    NaN
108          NaN     NaN                    NaN                    NaN
109          NaN     NaN                    NaN                    NaN
115          NaN     NaN                    NaN                    NaN
120          NaN     NaN                    NaN                    NaN
127          NaN     NaN                    NaN                    NaN
133          NaN     NaN                    NaN                    NaN
145          NaN     NaN                    NaN                    NaN
146          NaN     NaN                    NaN                    NaN
148          NaN     NaN                    NaN                    NaN

In [216]:
print("now the HV 3W trafos")
print(net.trafo3w.loc[(net.trafo3w.vn_hv_kv > 100) & (net.trafo3w.vn_hv_kv < 150)])

now the HV 3W trafos
           name std_type  hv_bus  mv_bus  lv_bus  sn_hv_mva  sn_mv_mva  \
0           GT1     None    9001   10064    2409    60.6000    30.3000
1           GT3     None    3512    7750   10142    66.6000    33.3000
2           GT2     None    4179     278    9035    60.6000    30.3000
4            T2     None    1223     631    8844    60.6000    30.3000
5           GT2     None    2889    8029    5052    66.6000    33.3000
6           GT2     None    3028      49   10037    60.6000    30.3000
7           GT2     None    5922    3176    5989    66.6000    33.3000
8   LPN 0044(4)     None    8175    2075    7664    85.0000    42.5000
9   LPN 0006(2)     None    7105    2297    3834    60.6000    30.3000
10          GT5     None    2815     710    2141    90.0000    45.0000
11         GT1A     None    4457    7675    8884    66.6600    33.3300
12          GT1     None    5622    9282    4725    66.6600    33.3300
13          GT2     None    1343    9591    1406    66.6000    33.3000
14         GT3E     None    2805    7514    1191    66.6000    33.3000
15          GT1     None   10611    8827    7315    66.6000    33.3000
17          GT4     None    7589    3944    2965    60.6000    30.3000
18          GT3     None    6316    6693    8570    66.6000    33.3000
19          GT1     None    9365    6127    9429    66.6000    33.3000
20          GT2     None    4996    4351    3071    66.6000    33.3000
21          GT1     None    5713    4047    4122    66.6000    33.3000
22          GT1     None     152    9484    3527    60.6000    30.3000
23          GT1     None    6502    9720   10502    66.6000    33.3000
24          GT1     None    3764   10336   10628    66.6000    33.3000
25          GT2     None    3093    8211    3867    66.6000    33.3000
26         GT2E     None     185   10423    1902    66.6000    33.3000
27           T3     None    7951    3267    9426    60.6000    30.3000
28          GT1     None    5766    6945     451    60.6000    30.3000
29          GT2     None    8162    3888    8165    66.6000    33.3000
30          GT2     None    4681    7120    9108    60.6000    30.3000
31          GT1     None    8310    8237    9620    66.6000    33.3000
32          GT1     None    1610    8620     873    66.6000    33.3000
33         GT4B     None    7837    7044    6839    66.6000    33.3000
34          GT1     None    9561    3502    5362    60.6000    30.3000
35          GT1     None    6331    5874    6696    60.6000    30.3000
36         GT2B     None    5722    8044    7162    60.6000    30.3000
37          GT3     None    6284    7093    1589    66.6000    33.3000
38          GT3     None    4063    8786    2622    66.6000    33.3000
39          GT1     None    9934    1862    5976    66.6000    33.3000
40           T2     None    3821    8853    3566    60.6000    30.3000
41         GT1B     None     693   10412    7503    90.0000    45.0000
42          GT6     None    1170    5145    9506    66.6000    33.3000
43          GT1     None    8120    1901    1176    60.6000    30.3000
44          GT3     None    6775    5274    3359    66.6000    33.3000
45          GT1     None    7312    6747    2165    60.6000    30.3000
46          GT3     None     567    1563    3522    60.6000    30.3000
47          T1A     None     394    6532    3974    60.6000    30.3000
48          GT2     None    8850    5556    8822    66.6000    33.3000
49          GT3     None    1100    6644    1840    60.6000    30.3000
50          GT2     None    5414    1253    5658    66.6000    33.3000
51          GT2     None    1398   10284    3597    60.6000    30.3000
52          GT2     None    5509   10615    6923    66.6600    33.3300
54          GT2     None    4320    7186     900    66.6000    33.3000
55  LPN 0035(3)     None    9438    7122    6827    85.0000    42.5000
56          T2A     None    1294    6500     281    60.6000    30.3000
57          GT1     None    4627    1880     797    66.6600    33.3300
58         GT1B     None    3055    6140    6109    60.6000    30.3000
59           T1     None    7475    7165    1729    60.6000    30.3000
60         GT2A     None    9871    6451     342    66.6600    33.3300
61          GT5     None    4572    9743    1301    66.6000    33.3000
62           T3     None    5588    4153     504    60.6000    30.3000
63  LPN 0011(5)     None    8129    4201      28    66.6000    33.3000
64         GT1E     None    5055    2614    8982    66.6000    33.3000
65          GT3     None    2254    6069    4950    60.6000    30.3000
66  LPN 0011(6)     None    9192    3532   10378    66.6000    33.3000
67  LPN 0006(3)     None    7102    6595    3189    60.6000    30.3000
68          GT2     None     480    4395    9410    85.0000    42.5000
69          GT3     None    3774    3206    5795    60.6000    30.3000
70          GT1     None    2782    7324    1791    60.6000    30.3000
71           T4     None    5547   10257     852    76.0000    38.0000
72          GT3     None    2400    6930    6915    60.6000    30.3000
73          GT2     None    6767    1909    3655    60.6000    30.3000
74          GT2     None    6006    2140    2326    66.6000    33.3000
75  LPN 0044(3)     None    3517    8366    1538    85.0000    42.5000
76          GT1     None     119    2269    3907    60.6000    30.3000
77          GT3     None    8603    4739    2844    60.6000    30.3000
78  LPN 0035(4)     None     956    5429    1620    85.0000    42.5000
79          GT1     None    9318    4382    5022    85.0000    42.5000
80          GT3     None    3021    8087    7541    60.6000    30.3000
81          GT2     None    4876    2369    7323    60.6000    30.3000
82          GT2     None   10052    8505    9648    60.6000    30.3000
83           T1     None    8174    9963    5327    60.6000    30.3000
84  LPN 0030(2)     None    5091    8618    4787   120.0000    60.0000
85          GT4     None    4040    2304    3679    66.6000    33.3000
86          GT3     None    8835    7583    4501    66.6000    33.3000
87  LPN 0030(3)     None    1039    4665    3269   120.0000    60.0000
88          GT1     None    3988    4802    3704    66.6000    33.3000
89          GT2     None    7771    1918    9911    60.6000    30.3000
90          GT3     None    8011    5407    1208    60.6000    30.3000
91          GT2     None    7728    1256    1055    66.6600    33.3300
92          GT2     None    4465    8751    8034    60.6000    30.3000
93          GT1     None    2232    2892    6023    60.6000    30.3000
94          GT2     None      96    1116    9678    60.6000    30.3000
95          GT3     None    3899    4879    9748    60.6000    30.3000
96          GT1     None    8654    6469    9259    66.6000    33.3000

    sn_lv_mva  vn_hv_kv  vn_mv_kv  ...  vkr0_hv_percent  vkr0_mv_percent  \
0     30.3000  132.0000   11.1100  ...              NaN              NaN
1     33.3000  132.0000   11.1100  ...              NaN              NaN
2     30.3000  132.0000   11.1100  ...              NaN              NaN
4     30.3000  132.0000   11.1100  ...              NaN              NaN
5     33.3000  132.0000   11.1100  ...              NaN              NaN
6     30.3000  132.0000   11.1100  ...              NaN              NaN
7     33.3000  132.0000   11.1100  ...              NaN              NaN
8     42.5000  132.0000   22.0000  ...              NaN              NaN
9     30.3000  132.0000   11.1100  ...              NaN              NaN
10    45.0000  132.0000   20.0000  ...              NaN              NaN
11    33.3300  132.0000   11.1100  ...              NaN              NaN
12    33.3300  132.0000   11.1100  ...              NaN              NaN
13    33.3000  132.0000   11.1100  ...              NaN              NaN
14    33.3000  132.0000   11.1100  ...              NaN              NaN
15    33.3000  132.0000   11.1100  ...              NaN              NaN
17    30.3000  132.0000   11.1100  ...              NaN              NaN
18    33.3000  132.0000   11.1100  ...              NaN              NaN
19    33.3000  132.0000   11.1100  ...              NaN              NaN
20    33.3000  132.0000   11.1100  ...              NaN              NaN
21    33.3000  132.0000   11.1100  ...              NaN              NaN
22    30.3000  132.0000   11.1100  ...              NaN              NaN
23    33.3000  132.0000   11.1100  ...              NaN              NaN
24    33.3000  132.0000   11.1100  ...              NaN              NaN
25    33.3000  132.0000   11.1100  ...              NaN              NaN
26    33.3000  132.0000   11.1100  ...              NaN              NaN
27    30.3000  132.0000   11.1100  ...              NaN              NaN
28    30.3000  132.0000   11.1100  ...              NaN              NaN
29    33.3000  132.0000   11.1100  ...              NaN              NaN
30    30.3000  132.0000   11.1100  ...              NaN              NaN
31    33.3000  132.0000   11.1100  ...              NaN              NaN
32    33.3000  132.0000   11.1100  ...              NaN              NaN
33    33.3000  132.0000   11.1100  ...              NaN              NaN
34    30.3000  132.0000   11.1100  ...              NaN              NaN
35    30.3000  132.0000   11.1100  ...              NaN              NaN
36    30.3000  132.0000   11.1100  ...              NaN              NaN
37    33.3000  132.0000   11.1100  ...              NaN              NaN
38    33.3000  132.0000   11.1100  ...              NaN              NaN
39    33.3000  132.0000   11.1100  ...              NaN              NaN
40    30.3000  132.0000   11.1100  ...              NaN              NaN
41    45.0000  132.0000   20.0000  ...              NaN              NaN
42    33.3000  132.0000   11.1100  ...              NaN              NaN
43    30.3000  132.0000   11.1100  ...              NaN              NaN
44    33.3000  132.0000   11.1100  ...              NaN              NaN
45    30.3000  132.0000   11.1100  ...              NaN              NaN
46    30.3000  132.0000   11.1100  ...              NaN              NaN
47    30.3000  132.0000   11.1100  ...              NaN              NaN
48    33.3000  132.0000   11.1100  ...              NaN              NaN
49    30.3000  132.0000   11.1100  ...              NaN              NaN
50    33.3000  132.0000   11.1100  ...              NaN              NaN
51    30.3000  132.0000   11.1100  ...              NaN              NaN
52    33.3300  132.0000   11.1100  ...              NaN              NaN
54    33.3000  132.0000   11.1100  ...              NaN              NaN
55    42.5000  132.0000   22.0000  ...              NaN              NaN
56    30.3000  132.0000   11.1100  ...              NaN              NaN
57    33.3300  132.0000   11.1100  ...              NaN              NaN
58    30.3000  132.0000   11.1100  ...              NaN              NaN
59    30.3000  132.0000   11.1100  ...              NaN              NaN
60    33.3300  132.0000   11.1100  ...              NaN              NaN
61    33.3000  132.0000   11.1100  ...              NaN              NaN
62    30.3000  132.0000   11.1100  ...              NaN              NaN
63    33.3000  132.0000   11.1100  ...              NaN              NaN
64    33.3000  132.0000   11.1100  ...              NaN              NaN
65    30.3000  132.0000   11.1100  ...              NaN              NaN
66    33.3000  132.0000   11.1100  ...              NaN              NaN
67    30.3000  132.0000   11.1100  ...              NaN              NaN
68    42.5000  132.0000   22.0000  ...              NaN              NaN
69    30.3000  132.0000   11.1100  ...              NaN              NaN
70    30.3000  132.0000   11.1100  ...              NaN              NaN
71    38.0000  132.0000   11.1100  ...              NaN              NaN
72    30.3000  132.0000   11.1100  ...              NaN              NaN
73    30.3000  132.0000   11.1100  ...              NaN              NaN
74    33.3000  132.0000   11.1100  ...              NaN              NaN
75    42.5000  132.0000   22.0000  ...              NaN              NaN
76    30.3000  132.0000   11.1100  ...              NaN              NaN
77    30.3000  132.0000   11.1100  ...              NaN              NaN
78    42.5000  132.0000   22.0000  ...              NaN              NaN
79    42.5000  132.0000   22.0000  ...              NaN              NaN
80    30.3000  132.0000   11.1100  ...              NaN              NaN
81    30.3000  132.0000   11.1100  ...              NaN              NaN
82    30.3000  132.0000   11.1100  ...              NaN              NaN
83    30.3000  132.0000   11.1100  ...              NaN              NaN
84    60.0000  132.0000   22.0000  ...              NaN              NaN
85    33.3000  132.0000   11.1100  ...              NaN              NaN
86    33.3000  132.0000   11.1100  ...              NaN              NaN
87    60.0000  132.0000   22.0000  ...              NaN              NaN
88    33.3000  132.0000   11.1100  ...              NaN              NaN
89    30.3000  132.0000   11.1100  ...              NaN              NaN
90    30.3000  132.0000   11.1100  ...              NaN              NaN
91    33.3300  132.0000   11.1100  ...              NaN              NaN
92    30.3000  132.0000   11.1100  ...              NaN              NaN
93    30.3000  132.0000   11.1100  ...              NaN              NaN
94    30.3000  132.0000   11.1100  ...              NaN              NaN
95    30.3000  132.0000   11.1100  ...              NaN              NaN
96    33.3000  132.0000   11.1100  ...              NaN              NaN

    vkr0_lv_percent  CurrentLimit.value_hv  CurrentLimit.value_mv  \
0               NaN                    NaN                    NaN
1               NaN                    NaN                    NaN
2               NaN                    NaN                    NaN
4               NaN                    NaN                    NaN
5               NaN                    NaN                    NaN
6               NaN                    NaN                    NaN
7               NaN                    NaN                    NaN
8               NaN                    NaN                    NaN
9               NaN                    NaN                    NaN
10              NaN                    NaN                    NaN
11              NaN                    NaN                    NaN
12              NaN                    NaN                    NaN
13              NaN                    NaN                    NaN
14              NaN                    NaN                    NaN
15              NaN                    NaN                    NaN
17              NaN                    NaN                    NaN
18              NaN                    NaN                    NaN
19              NaN                    NaN                    NaN
20              NaN                    NaN                    NaN
21              NaN                    NaN                    NaN
22              NaN                    NaN                    NaN
23              NaN                    NaN                    NaN
24              NaN                    NaN                    NaN
25              NaN                    NaN                    NaN
26              NaN                    NaN                    NaN
27              NaN                    NaN                    NaN
28              NaN                    NaN                    NaN
29              NaN                    NaN                    NaN
30              NaN                    NaN                    NaN
31              NaN                    NaN                    NaN
32              NaN                    NaN                    NaN
33              NaN                    NaN                    NaN
34              NaN                    NaN                    NaN
35              NaN                    NaN                    NaN
36              NaN                    NaN                    NaN
37              NaN                    NaN                    NaN
38              NaN                    NaN                    NaN
39              NaN                    NaN                    NaN
40              NaN                    NaN                    NaN
41              NaN                    NaN                    NaN
42              NaN                    NaN                    NaN
43              NaN                    NaN                    NaN
44              NaN                    NaN                    NaN
45              NaN                    NaN                    NaN
46              NaN                    NaN                    NaN
47              NaN                    NaN                    NaN
48              NaN                    NaN                    NaN
49              NaN                    NaN                    NaN
50              NaN                    NaN                    NaN
51              NaN                    NaN                    NaN
52              NaN                    NaN                    NaN
54              NaN                    NaN                    NaN
55              NaN                    NaN                    NaN
56              NaN                    NaN                    NaN
57              NaN                    NaN                    NaN
58              NaN                    NaN                    NaN
59              NaN                    NaN                    NaN
60              NaN                    NaN                    NaN
61              NaN                    NaN                    NaN
62              NaN                    NaN                    NaN
63              NaN                    NaN                    NaN
64              NaN                    NaN                    NaN
65              NaN                    NaN                    NaN
66              NaN                    NaN                    NaN
67              NaN                    NaN                    NaN
68              NaN                    NaN                    NaN
69              NaN                    NaN                    NaN
70              NaN                    NaN                    NaN
71              NaN                    NaN                    NaN
72              NaN                    NaN                    NaN
73              NaN                    NaN                    NaN
74              NaN                    NaN                    NaN
75              NaN                    NaN                    NaN
76              NaN                    NaN                    NaN
77              NaN                    NaN                    NaN
78              NaN                    NaN                    NaN
79              NaN                    NaN                    NaN
80              NaN                    NaN                    NaN
81              NaN                    NaN                    NaN
82              NaN                    NaN                    NaN
83              NaN                    NaN                    NaN
84              NaN                    NaN                    NaN
85              NaN                    NaN                    NaN
86              NaN                    NaN                    NaN
87              NaN                    NaN                    NaN
88              NaN                    NaN                    NaN
89              NaN                    NaN                    NaN
90              NaN                    NaN                    NaN
91              NaN                    NaN                    NaN
92              NaN                    NaN                    NaN
93              NaN                    NaN                    NaN
94              NaN                    NaN                    NaN
95              NaN                    NaN                    NaN
96              NaN                    NaN                    NaN


## Get MV Loads and Generation

In [217]:
print("now the loads")
net.load['vn_kv_bus'] = net.load.bus.map(net.bus.vn_kv)
print(net.load.loc[(net.load.vn_kv_bus == 11)].head(10))

now the loads
   name   bus   p_mw  q_mvar  const_z_p_percent  const_i_p_percent  \
0    W2  7547 1.8105  0.4538             0.0000             0.0000
1    E1  9988 1.6625  0.3376             0.0000             0.0000
3    E1  1749 2.4200  0.4914             0.0000             0.0000
4   SE2  6411 2.2200  0.6475             0.0000             0.0000
5   WH5  8445 1.2659  0.4595             0.0000             0.0000
6   MP1   178 1.8765  0.4703             0.0000             0.0000
7    B1  2375 1.5333  0.5040             0.0000             0.0000
8   SD3   188 0.2882  0.0841             0.0000             0.0000
9   NE2  8775 1.8625  0.4668             0.0000             0.0000
10  WA2  9529 0.1750  0.0510             0.0000             0.0000

    const_z_q_percent  const_i_q_percent  sn_mva  scaling  in_service  type  \
0              0.0000             0.0000     NaN   1.0000        True  None
1              0.0000             0.0000     NaN   1.0000        True  None
3              0.0000             0.0000     NaN   1.0000        True  None
4              0.0000             0.0000     NaN   1.0000        True  None
5              0.0000             0.0000     NaN   1.0000        True  None
6              0.0000             0.0000     NaN   1.0000        True  None
7              0.0000             0.0000     NaN   1.0000        True  None
8              0.0000             0.0000     NaN   1.0000        True  None
9              0.0000             0.0000     NaN   1.0000        True  None
10             0.0000             0.0000     NaN   1.0000        True  None

                                origin_id    origin_class  \
0   _001042be-8d96-4f41-bcea-c835cdac77fb  EnergyConsumer
1   _00118c97-34aa-43a3-ac1a-65ffa9f0eb4c  EnergyConsumer
3   _00735870-5af6-439a-8289-03d1e2d57cc8  EnergyConsumer
4   _007b4da1-93e2-401b-ba8a-fefd13624d17  EnergyConsumer
5   _008c249d-c891-4b56-b2ff-888e5ad834b0  EnergyConsumer
6   _009f64da-277b-4747-90d4-bbf690e9b2b9  EnergyConsumer
7   _00a50199-e099-42ae-91fd-880db3d8d89e  EnergyConsumer
8   _00cf7970-d10e-4f78-b933-9bc31ed566fd  EnergyConsumer
9   _00e1ffee-8401-4c35-9127-70bbe3f8e4ba  EnergyConsumer
10  _00e48e1b-0a5a-4257-a3b0-909d30125700  EnergyConsumer

                                 terminal description  vn_kv_bus
0   _172fc73f-33ec-9899-2c3b-66203a28cc94         NaN    11.0000
1   _89fbcb99-2be0-b958-7ec2-caad9d6a5e3c         NaN    11.0000
3   _5d5851c1-8dbc-d22e-2f5a-2988f72bcd2e         NaN    11.0000
4   _952ec396-efc9-9f0a-de1a-032c7166e53e         NaN    11.0000
5   _10b35d5c-5bdd-644f-6e82-7bc376b0e1bb         NaN    11.0000
6   _3441a7d3-06b7-6493-801d-3f19bac66cba         NaN    11.0000
7   _21ebe53d-b846-5bc2-86ba-a11f1c29362f         NaN    11.0000
8   _9ac1ee7b-088a-8935-98b1-9d402b8e2b4c         NaN    11.0000
9   _a49a1d94-a14c-5fcc-54ae-fe1cbc65d2b7         NaN    11.0000
10  _60876963-b7bf-df43-4116-9c1a0526ea73         NaN    11.0000

In [218]:
print("now the PQ generators")
net.sgen['vn_kv_bus'] = net.sgen.bus.map(net.bus.vn_kv)
print(net.sgen.loc[(net.sgen.vn_kv_bus == 11)].head(10))

now the PQ generators
                       name   bus    p_mw  q_mvar  min_q_mvar  max_q_mvar  \
2  REI_B12_PQ__Plus__030deg   700 -0.0000 -0.0000         NaN         NaN
3   REI_B3_PV__Plus__059deg  9442 -0.0000 -0.0000         NaN         NaN
6   REI_B3_PQ__Plus__030deg  6431 -0.0000 -0.0000         NaN         NaN
7  REI_B3_PQ__Minus__030deg  2330 -0.0000 -0.0000         NaN         NaN

   sn_mva  scaling  controllable  id_q_capability_characteristic  ... vn_kv  \
2     NaN   1.0000         False                            <NA>  ...   NaN
3     NaN   1.0000         False                            <NA>  ...   NaN
6     NaN   1.0000         False                            <NA>  ...   NaN
7     NaN   1.0000         False                            <NA>  ...   NaN

  rdss_ohm  xdss_pu lrc_pu  RegulatingControl.targetValue referencePriority  \
2      NaN      NaN    NaN                            NaN            0.0000
3      NaN      NaN    NaN                            NaN            0.0000
6      NaN      NaN    NaN                            NaN            0.0000
7      NaN      NaN    NaN                            NaN            0.0000

  max_p_mw min_p_mw RegulatingControl.enabled vn_kv_bus
2      NaN      NaN                      <NA>   11.0000
3      NaN      NaN                      <NA>   11.0000
6      NaN      NaN                      <NA>   11.0000
7      NaN      NaN                      <NA>   11.0000

[4 rows x 33 columns]

# Run a power flow

#### Pre-processing steps for power flow execution
The following blocks of code provide functions to apply the adjustments necessary to successfully run the power flow on the UK Power Networks grids. These adjustments are required due to differences in how the pandapower library handles network data compared with other power system software tools, such as PowerFactory. Examples include the creation of external grids (*slack buses* in power flow terminology) and the replacement of zero-impedance components with switches.

In [219]:
# Function to replace components with very small impedance with switches.
from pandapower.toolbox import create_replacement_switch_for_branch

def _replace_zero_impedance_components(net):
    min_ohm = 0.001
    to_replace = (np.abs(net.line.x_ohm_per_km * net.line.length_km) <= min_ohm) & net.line.in_service

    if np.any(to_replace):
        print(f"replaced {sum(to_replace)} lines with switches")

    for i in net.line.loc[to_replace].index.values:
        create_replacement_switch_for_branch(net, "line", i)
        net.line.at[i, "in_service"] = False

    xward = net.xward.loc[(np.abs(net.xward.x_ohm) <= min_ohm) & net.xward.in_service].index.values
    if len(xward) > 0:
        pp.replace_xward_by_ward(net, index=xward, drop=False)
        print(f"replaced {len(xward)} xwards with wards")

    zb_f_ohm = np.square(net.bus.loc[net.impedance.from_bus.values, "vn_kv"].values) / net.impedance.sn_mva
    zb_t_ohm = np.square(net.bus.loc[net.impedance.to_bus.values, "vn_kv"].values) / net.impedance.sn_mva
    impedance = ((np.abs(net.impedance.xft_pu) <= min_ohm / zb_f_ohm) |
                (np.abs(net.impedance.xtf_pu) <= min_ohm / zb_t_ohm)) & net.impedance.in_service

    if any(impedance):
        print(f"replaced {sum(impedance)} impedance elements with switches")

    for i in net.impedance.loc[impedance].index.values:
        pp.create_replacement_switch_for_branch(net, "impedance", i)
        net.impedance.at[i, "in_service"] = False

In [220]:
# Function to apply the needed preprocessing steps
def apply_preprocessing(net, license_area):
    # Here zero impedance components are  modified to switches to prevent ill-conditioning
    net.impedance.drop(net.impedance.index, inplace=True)
    net.line["c_nf_per_km"] *= 0.1
    _replace_zero_impedance_components(net)
    
    # Here powers are scaled down, as Excel tables provided max demand values. 
    # When using SSH profiles, it will be possible to avoid this.
    net.load["p_mw"] *= 0.1
    net.load["q_mvar"] *= 0.1
    net.sgen["p_mw"] *= 0.5
    net.sgen["q_mvar"] *= 0.5

    # Here slack buses are defined for each grid. 
    # Slack buses will be defined in the SSH profiles, so this steps won't be needed 
    # when using the full CIM data with SSH profiles.
    if license_area == "LPN":
        pp.create_ext_grid(net,bus=10711,vm_pu=1)
        pp.create_ext_grid(net,bus=10699,vm_pu=1)
        pp.create_ext_grid(net,bus=10674,vm_pu=1)
        pp.create_ext_grid(net,bus=10738,vm_pu=1)
        pp.create_ext_grid(net,bus=10673,vm_pu=1)
    elif license_area == "SPN":
        pp.create_ext_grid(net,bus=4899,vm_pu=1)
        pp.create_ext_grid(net,bus=4879,vm_pu=1)
        pp.create_ext_grid(net,bus=4903,vm_pu=1)
        pp.create_ext_grid(net,bus=4920,vm_pu=1)
        pp.create_ext_grid(net,bus=4916,vm_pu=1)
        pp.create_ext_grid(net,bus=4925,vm_pu=1)
        pp.create_ext_grid(net,bus=4878,vm_pu=1)
    elif license_area == "EPN":
        pp.create_ext_grid(net,bus=9906,vm_pu=1)
        pp.create_ext_grid(net,bus=9918,vm_pu=1)
        pp.create_ext_grid(net,bus=9900,vm_pu=1)
        pp.create_ext_grid(net,bus=9910,vm_pu=1)
        pp.create_ext_grid(net,bus=9878,vm_pu=1)
    else:
        raise ValueError("Sorry, this license area does not exist in UK Power Networks. Allowed areas are LPN, SPN and EPN.")

    return net

In [221]:
# Apply the pre-processing steps on the selected grid
license_area = "LPN"  # Provide here the name of the considered license area. It should be "LPN", "SPN", or "EPN".
if net.bus.index.size > 1:
    net = apply_preprocessing(net, license_area)

replaced 154 lines with switches

## Run a power flow study
One of the easiest tasks that can be done with pandapower is to run a power flow. 
This allows analysing the voltage conditions in the grid and the powers/currents flowing through the different lines and components of the network, considering the load and generation available as input. 

Through a power flow calculation it is possible to make a contingency analysis, namely to assess if the operating conditions of the grid are within the allowed boundaries.

In this section, you will see: 
- How to run a power flow and visualize the results
- How to filter the power flow results
- How to identify possible contingencies (overloading or voltage violations)

In [222]:
# Run a power flow
if len(net.bus) == 0:
    bus = pp.create_bus(net, vn_kv=132)
    pp.create_ext_grid(net, bus=bus)
pp.runpp(net, max_iteration=50)

## Visualize the power flow results
In the bus results table you will find the resulting bus voltage and power consumption / injection at each bus

In [223]:
# Visualize bus results
display(net.res_bus.loc[:5])
display("Maximum voltage magnitude in the grid (per unit): " + "{:.4f}".format(np.nanmax(net.res_bus.vm_pu)))
display("Minimum voltage magnitude in the grid (per unit): " + "{:.4f}".format(np.nanmin(net.res_bus.vm_pu)))

   vm_pu  va_degree   p_mw  q_mvar
0 1.0000     0.0000 0.0000  0.0000
1 0.9781    -5.6045 0.1819  0.0456
2 0.9423   -11.4989 0.4500  0.1313
3 0.9943    -1.1768 0.0000  0.0000
4 0.9762    -6.0355 0.2230  0.0650
5 0.9872   -11.4144 0.0000  0.0000

'Maximum voltage magnitude in the grid (per unit): 1.0492'

'Minimum voltage magnitude in the grid (per unit): 0.8657'

Some of the bus results may have NaN. This happens for those buses that are disconnected from the main grid.

In [224]:
# Visualize number of connected buses
num_disconnected_buses = np.sum(np.isnan(net.res_bus.vm_pu))
num_connected_buses = np.sum(~np.isnan(net.res_bus.vm_pu))
total_num_buses = len(net.bus)
percentage_connected_buses = 100 * num_connected_buses / total_num_buses
display("Percentage of connected buses: " + "{:.2f}".format(percentage_connected_buses) + "%")

'Percentage of connected buses: 92.29%'

In the line and transformer result tables you can see, among others, the level of power flowing through these components.

In [225]:
# Visualize line results
display(net.res_trafo.loc[:5])

,p_hv_mw,q_hv_mvar,p_lv_mw,q_lv_mvar,pl_mw,ql_mvar,i_hv_ka,i_lv_ka,vm_hv_pu,va_hv_degree,vm_lv_pu,va_lv_degree,loading_percent
0,0.4684,0.1565,-0.4682,-0.1537,0.0002,0.0028,0.0131,0.0437,0.9891,-17.4632,0.9869,-17.7661,4.9932
1,1.8893,0.2624,-1.8460,-0.1564,0.0432,0.1061,0.0084,0.0325,0.9979,-0.1122,0.9972,-0.3770,3.1858
2,0.7370,0.1915,-0.7368,-0.1845,0.0003,0.0070,0.0134,0.0401,0.9962,-0.4892,0.9937,-0.9954,5.0959
3,-3.2927,-0.8838,3.3091,1.1417,0.0163,0.2579,0.0683,0.2019,0.8739,-17.5752,0.9099,-15.0219,26.2892
4,1.9671,0.5275,-1.9228,-0.4115,0.0443,0.1160,0.0091,0.0530,0.9752,-3.9193,0.9739,-4.1673,3.4807
5,0.8642,0.2177,-0.8638,-0.2083,0.0004,0.0094,0.0161,0.0484,0.9667,-4.5656,0.9638,-5.1460,6.1459

In [226]:
# Visualize transformer results
display(net.res_trafo.loc[:5])

,p_hv_mw,q_hv_mvar,p_lv_mw,q_lv_mvar,pl_mw,ql_mvar,i_hv_ka,i_lv_ka,vm_hv_pu,va_hv_degree,vm_lv_pu,va_lv_degree,loading_percent
0,0.4684,0.1565,-0.4682,-0.1537,0.0002,0.0028,0.0131,0.0437,0.9891,-17.4632,0.9869,-17.7661,4.9932
1,1.8893,0.2624,-1.8460,-0.1564,0.0432,0.1061,0.0084,0.0325,0.9979,-0.1122,0.9972,-0.3770,3.1858
2,0.7370,0.1915,-0.7368,-0.1845,0.0003,0.0070,0.0134,0.0401,0.9962,-0.4892,0.9937,-0.9954,5.0959
3,-3.2927,-0.8838,3.3091,1.1417,0.0163,0.2579,0.0683,0.2019,0.8739,-17.5752,0.9099,-15.0219,26.2892
4,1.9671,0.5275,-1.9228,-0.4115,0.0443,0.1160,0.0091,0.0530,0.9752,-3.9193,0.9739,-4.1673,3.4807
5,0.8642,0.2177,-0.8638,-0.2083,0.0004,0.0094,0.0161,0.0484,0.9667,-4.5656,0.9638,-5.1460,6.1459

You can visualize the results for a specific element

In [227]:
# Visualize bus results at a selected bus
bus_idx = 178
if bus_idx in net.res_bus.index:
    print(net.res_bus.loc[bus_idx])
else:
    print("The given bus does not exist")

vm_pu        0.9700
va_degree   -4.9735
p_mw         0.1876
q_mvar       0.0470
Name: 178, dtype: float64

In [228]:
# Visualize results at a selected transformer
trafo_idx = 15
if trafo_idx in net.res_trafo.index:
    print(net.res_trafo.loc[trafo_idx])
else:
    print("The given transformer does not exist")

p_hv_mw            0.8523
q_hv_mvar         -0.2747
p_lv_mw           -0.8522
q_lv_mvar          0.3094
pl_mw              0.0000
ql_mvar            0.0347
i_hv_ka            0.0040
i_lv_ka            0.0163
vm_hv_pu           0.9740
va_hv_degree      -4.4167
vm_lv_pu           0.9747
va_lv_degree      -4.5499
loading_percent    1.0335
Name: 15, dtype: float64

## Sort the results 
You can easily sort the results using the *sort_values* function

In [229]:
# Sort bus results from buses with the smallest voltage
net.res_bus.sort_values("vm_pu").head(5)

      vm_pu  va_degree   p_mw  q_mvar
2471 0.8657   -17.8511 0.0000  0.0000
6098 0.8657   -17.8530 0.0000  0.0000
7634 0.8658   -17.8435 0.0000  0.0000
4460 0.8659   -17.8452 0.0000  0.0000
6463 0.8659   -17.8533 0.0000  0.0000

In [230]:
# Sort line results from lines with highest active power flow
net.res_line.sort_values("p_from_mw", ascending=False).head(5)

,p_from_mw,q_from_mvar,p_to_mw,q_to_mvar,pl_mw,ql_mvar,i_from_ka,i_to_ka,i_ka,vm_from_pu,va_from_degree,vm_to_pu,va_to_degree,loading_percent
538,134.4007,-5.2952,-133.8342,5.8453,0.5665,0.5501,0.6009,0.6008,0.6009,0.9790,-3.4636,0.9752,-3.9193,NaN
708,132.2813,-8.9497,-131.8767,9.3321,0.4046,0.3825,0.5925,0.5924,0.5925,0.9787,-3.4619,0.9761,-3.7962,NaN
617,126.8456,-9.6059,-126.7513,9.5901,0.0942,-0.0158,0.5706,0.5704,0.5706,0.9752,-3.9193,0.9747,-4.1113,NaN
389,126.8456,-9.6059,-126.7513,9.5901,0.0942,-0.0158,0.5706,0.5704,0.5706,0.9752,-3.9193,0.9747,-4.1113,NaN
380,124.8627,-8.9600,-124.8083,8.3419,0.0544,-0.6181,0.5617,0.5615,0.5617,0.9747,-4.1113,0.9744,-4.2323,NaN

## Filter the results 
You can filter the results as you like, selecting only specific types or clusters of elements, or specific columns of the tables

In [231]:
# Visualize bus results only for buses at 132 kV
net.res_bus[net.bus.vn_kv==132].head(5)

    vm_pu  va_degree   p_mw  q_mvar
0  1.0000     0.0000 0.0000  0.0000
16 0.9740    -4.4157 0.0000  0.0000
45 0.9752    -3.9193 0.0000  0.0000
54 0.9980    -0.1132 0.0000  0.0000
58 0.9979    -0.0951 0.0000  0.0000

In [232]:
# Visualize transformer results only for 132 kV/33 kV  transformers 
net.res_trafo[(net.trafo.vn_hv_kv==132) & (net.trafo.vn_lv_kv==33)].head(5)

,p_hv_mw,q_hv_mvar,p_lv_mw,q_lv_mvar,pl_mw,ql_mvar,i_hv_ka,i_lv_ka,vm_hv_pu,va_hv_degree,vm_lv_pu,va_lv_degree,loading_percent
1,1.8893,0.2624,-1.8460,-0.1564,0.0432,0.1061,0.0084,0.0325,0.9979,-0.1122,0.9972,-0.3770,3.1858
15,0.8523,-0.2747,-0.8522,0.3094,0.0000,0.0347,0.0040,0.0163,0.9740,-4.4167,0.9747,-4.5499,1.0335
26,6.2574,1.4172,-6.1979,-1.0878,0.0595,0.3294,0.0281,0.1105,1.0000,-0.0004,0.9964,-0.9005,7.1287
58,0.0160,0.0670,0.0000,0.0000,0.0160,0.0670,0.0003,0.0000,0.9740,-4.4157,0.9739,-4.4170,0.1178
63,-0.0000,0.0000,0.0000,-0.0000,0.0000,0.0000,0.0000,0.0000,0.9823,-2.7178,0.9823,-2.7178,0.0000

In [233]:
# Visualize only active and reactive powers of the lines
net.res_line[["p_from_mw", "q_from_mvar", "p_to_mw", "q_to_mvar"]].head(5)

   p_from_mw  q_from_mvar   p_to_mw  q_to_mvar
0     1.8853       0.4704   -1.8852    -0.6192
1     0.0006      -0.0762   -0.0006     0.0134
2     0.0000       0.0000    0.0000     0.0000
3   124.8627      -8.9600 -124.8083     8.3419
4     0.8931       0.4482   -0.8929    -0.7239

## Detect contingencies
You can easily identify possible voltage contingencies in the grid, namely voltage values beyond the allowed thresholds.

In [234]:
# Check possible voltage violations
# Define voltage boundaries
lower_v_threshold = 0.90   # Define the lower boundary of the voltage magnitude (in per unit)
upper_v_threshold = 1.10   # Define the upper boundary of the voltage magnitude (in per unit)

# Check for overvoltages
if np.any(net.res_bus.vm_pu > upper_v_threshold):
    display("Overvoltages are present in the grid. Maximum voltage is: " + "{:.4f}".format(np.nanmax(net.res_bus.vm_pu)) + " p.u.")
    buses_with_overvoltage = net.bus.index[net.res_bus.vm_pu>upper_v_threshold]
    print("Buses with overvoltage:")
    print(buses_with_overvoltage)
else: 
    display("No overvoltages are present in the grid")

# Check for undervoltages
if np.any(net.res_bus.vm_pu < lower_v_threshold):
    display("Undervoltages are present in the grid. Minimum voltage is: " + "{:.4f}".format(np.nanmin(net.res_bus.vm_pu)) + " p.u.")
    buses_with_undervoltage = net.bus.index[net.res_bus.vm_pu<lower_v_threshold]
    print("Buses with undervoltage:")
    print(buses_with_undervoltage)
else: 
    display("No undervoltages are present in the grid")

'No overvoltages are present in the grid'

'Undervoltages are present in the grid. Minimum voltage is: 0.8657 p.u.'

Buses with undervoltage:
Index([   12,    42,    97,   102,   134,   153,   174,   230,   307,   322,
       ...
       10578, 10582, 10591, 10639, 10678, 10687, 10693, 10720, 10726, 10739],
      dtype='int64', length=256)

You can easily check if any overloading exists in the grid (**NB**: the possibility of verifying overloadings depends on the availability of rated values for lines and/or transformers).

In [235]:
# Check overloadings for transformers

overloading_factor = 1  # You can define an overloading factor if you desire to check overloadings for values different from 100%
if np.any(net.res_trafo.loading_percent > 100*overloading_factor):
    display("Overloading present in the grid transformers. Maximum loading is: " + "{:.2f}".format(np.nanmax(net.res_trafo.loading_percent)) + "%")
else: 
    display("No overloading is present in the grid transformers. Maximum loading is: " + "{:.2f}".format(np.nanmax(net.res_trafo.loading_percent)) + "%")

'Overloading present in the grid transformers. Maximum loading is: 108.94%'

In [236]:
# Visualize transformer loading (results sorted by the largest loading)
net.res_trafo[["loading_percent"]].sort_values("loading_percent", ascending=False).head(5)

     loading_percent
24          108.9383
164          59.6218
310          59.6178
399          33.4610
3            26.2892

# Use Case Study: Headroom capacity
#### Impact of new load or generation connections

Headroom capacity studies are a common use case that can be addressed leveraging the pandapower power flow libraries. The goal is to understand how much load or generation can be connected to a bus, before exceeding the allowed boundaries (voltage boundaries or overloading of the grid components).

In this section you will see:
- How to add new loads or generators to the grid
- How to discover the maximum load or generation that can be added at a bus before exceeding the operational boundaries (i.e., voltage or overloading limits)

"In this use case study, a new load and generation connection to the Barking West 11kV busbar is analysed. The single line diagram is available on [the LTDS landing page](https://ukpowernetworks.opendatasoft.com/explore/assets/long-term-development-statement/view/) on UK Power Networks' Open Data Portal.

#### 1. Derive the data for the busbar "BARW52 BB1"

In [237]:
# Get the index of the bus with the name "BARW52 BB1"
BARW52_index = net.bus[net.bus["name"] == "BARW52 BB1"].index[0]
print("The index of searched bus is: " + str(BARW52_index))

The index of searched bus is: 8287

In [238]:
# Get the bus results before adding load to analyse their loading after the load is added
before_BARW52 = net.res_bus.loc[BARW52_index]
print(before_BARW52)

vm_pu         0.9038
va_degree   -18.1756
p_mw          0.0000
q_mvar        0.0000
Name: 8287, dtype: float64

### 2. Derive the data for the transformers "FT2" and "T3" connected to the busbar "BARW52 BB1".

In [239]:
# Get the indices of the nodes with the names "BARW3B" and "BARW3C" where trafos are connected to them
bus_ft2 = net.bus[net.bus["name"] == "BARW3B"].index[0]
bus_t3 = net.bus[net.bus["name"] == "BARW3C"].index[0]

print("BARW3B node index:", bus_ft2)
print("BARW3C node index:", bus_t3)

# Find the transformers connected to these nodes
trafo_ft2 = net.trafo[net.trafo["hv_bus"] == bus_ft2].index[0]
trafo_t3 = net.trafo[net.trafo["hv_bus"] == bus_t3].index[0]

print("FT2 trafo index:", trafo_ft2, "| name:", net.trafo.at[trafo_ft2, "name"])
print("T3 trafo index:", trafo_t3, "| name:", net.trafo.at[trafo_t3, "name"])

BARW3B node index: 4723
BARW3C node index: 10214
FT2 trafo index: 197 | name: FT2
T3 trafo index: 360 | name: T3

In [240]:
# Get the transformer results before adding load to analyse their loading after the load is added
before_ft2 = net.res_trafo.loc[trafo_ft2].copy()
before_t3 = net.res_trafo.loc[trafo_t3].copy()

print("Before adding load:")
print("FT2:\n", before_ft2)
print("T3:\n", before_t3)

Before adding load:
FT2:
 p_hv_mw             0.5906
q_hv_mvar           0.1803
p_lv_mw            -0.5833
q_lv_mvar          -0.1462
pl_mw               0.0073
ql_mvar             0.0341
i_hv_ka             0.0125
i_lv_ka             0.0349
vm_hv_pu            0.8663
va_hv_degree      -17.8374
vm_lv_pu            0.9038
va_lv_degree      -18.1756
loading_percent     3.9605
Name: 197, dtype: float64
T3:
 p_hv_mw             0.5906
q_hv_mvar           0.1803
p_lv_mw            -0.5833
q_lv_mvar          -0.1462
pl_mw               0.0073
ql_mvar             0.0341
i_hv_ka             0.0125
i_lv_ka             0.0349
vm_hv_pu            0.8663
va_hv_degree      -17.8374
vm_lv_pu            0.9038
va_lv_degree      -18.1756
loading_percent     3.9605
Name: 360, dtype: float64

### 3. Derive the data for the lines connected to the transformers "FT2" and "T3".

In [241]:
# Find and print lines connected to the transformers FT2 and T3 
lines_to_ft2 = net.line[net.line["to_bus"] == bus_ft2]
lines_to_t3 = net.line[net.line["to_bus"] == bus_t3]

print("Lines connected to FT2 (BARW3B):\n", lines_to_ft2[["name", "from_bus", "to_bus"]])
print("Lines connected to T3 (BARW3C):\n", lines_to_t3[["name", "from_bus", "to_bus"]])

Lines connected to FT2 (BARW3B):
                 name  from_bus  to_bus
343  lne_BARW_BARD_2      4795    4723
Lines connected to T3 (BARW3C):
                 name  from_bus  to_bus
358  lne_BARW_BARD_3      9764   10214

In [242]:
# Get and print the results for lines connected to the transformers FT2 and T3 
# before adding the new load

before_lines_ft2 = net.res_line.loc[lines_to_ft2.index]
before_lines_t3 = net.res_line.loc[lines_to_t3.index]

print("Results for lines at FT2:\n", before_lines_ft2)
print("Results for lines at T3:\n", before_lines_t3)

Results for lines at FT2:
      p_from_mw  q_from_mvar  p_to_mw  q_to_mvar  pl_mw  ql_mvar  i_from_ka  \
343     0.5906       0.1797  -0.5906    -0.1803 0.0000  -0.0006     0.0125

     i_to_ka   i_ka  vm_from_pu  va_from_degree  vm_to_pu  va_to_degree  \
343   0.0125 0.0125      0.8663        -17.8369    0.8663      -17.8374

     loading_percent
343              NaN
Results for lines at T3:
      p_from_mw  q_from_mvar  p_to_mw  q_to_mvar  pl_mw  ql_mvar  i_from_ka  \
358     0.5906       0.1797  -0.5906    -0.1803 0.0000  -0.0006     0.0125

     i_to_ka   i_ka  vm_from_pu  va_from_degree  vm_to_pu  va_to_degree  \
358   0.0125 0.0125      0.8663        -17.8369    0.8663      -17.8374

     loading_percent
358              NaN

## Add a new load 
A new load can be easily created with the *create_load" function of pandapower. It requires defining the bus to which the load will be connected and its active and reactive power.

In [243]:
# Create a new load at the desired bus
load_bus = BARW52_index

if load_bus not in net.bus.index:
    # if the bus not exists, it needs to be created first
    pp.create_bus(net, vn_kv=132, index=load_bus)
load_p = 1 #MW
load_q = 0 #MVAr
pp.create_load(net, bus=load_bus, p_mw=load_p, q_mvar=load_q)
net.load.tail(1)

,name,bus,p_mw,q_mvar,const_z_p_percent,const_i_p_percent,const_z_q_percent,const_i_q_percent,sn_mva,scaling,in_service,type,origin_id,origin_class,terminal,description,vn_kv_bus
2892,None,8287,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,1.0000,True,wye,NaN,NaN,NaN,NaN,NaN

In [244]:
# Run a power flow after adding the new load
pp.runpp(net, max_iteration=50)

In [245]:
# Get the bus results after adding load to analyse their loading after the load is added
after_BARW52 = net.res_bus.loc[BARW52_index]
print(after_BARW52)

vm_pu         0.8960
va_degree   -19.6192
p_mw          1.0000
q_mvar        0.0000
Name: 8287, dtype: float64

In [246]:
# Get the transformer results after adding load to analyse their loading after the load is added
after_ft2 = net.res_trafo.loc[trafo_ft2].copy()
after_t3 = net.res_trafo.loc[trafo_t3].copy()

print("After adding load:")
print("FT2:\n", after_ft2)
print("T3:\n", after_t3)

After adding load:
FT2:
 p_hv_mw             0.9242
q_hv_mvar           0.1851
p_lv_mw            -0.9167
q_lv_mvar          -0.1462
pl_mw               0.0075
ql_mvar             0.0389
i_hv_ka             0.0192
i_lv_ka             0.0544
vm_hv_pu            0.8590
va_hv_degree      -19.0765
vm_lv_pu            0.8960
va_lv_degree      -19.6192
loading_percent     6.0957
Name: 197, dtype: float64
T3:
 p_hv_mw             0.9242
q_hv_mvar           0.1851
p_lv_mw            -0.9167
q_lv_mvar          -0.1462
pl_mw               0.0075
ql_mvar             0.0389
i_hv_ka             0.0192
i_lv_ka             0.0544
vm_hv_pu            0.8590
va_hv_degree      -19.0765
vm_lv_pu            0.8960
va_lv_degree      -19.6192
loading_percent     6.0957
Name: 360, dtype: float64

In [247]:
comparison_ft2 = pd.DataFrame({"before": before_ft2, "after": after_ft2})
comparison_t3 = pd.DataFrame({"before": before_t3, "after": after_t3})

print("FT2 comparison:\n", comparison_ft2)
print("T3 comparison:\n", comparison_t3)

FT2 comparison:
                   before    after
p_hv_mw           0.5906   0.9242
q_hv_mvar         0.1803   0.1851
p_lv_mw          -0.5833  -0.9167
q_lv_mvar        -0.1462  -0.1462
pl_mw             0.0073   0.0075
ql_mvar           0.0341   0.0389
i_hv_ka           0.0125   0.0192
i_lv_ka           0.0349   0.0544
vm_hv_pu          0.8663   0.8590
va_hv_degree    -17.8374 -19.0765
vm_lv_pu          0.9038   0.8960
va_lv_degree    -18.1756 -19.6192
loading_percent   3.9605   6.0957
T3 comparison:
                   before    after
p_hv_mw           0.5906   0.9242
q_hv_mvar         0.1803   0.1851
p_lv_mw          -0.5833  -0.9167
q_lv_mvar        -0.1462  -0.1462
pl_mw             0.0073   0.0075
ql_mvar           0.0341   0.0389
i_hv_ka           0.0125   0.0192
i_lv_ka           0.0349   0.0544
vm_hv_pu          0.8663   0.8590
va_hv_degree    -17.8374 -19.0765
vm_lv_pu          0.9038   0.8960
va_lv_degree    -18.1756 -19.6192
loading_percent   3.9605   6.0957

In [248]:
# Get and print the results for lines connected to the transformers FT2 and T3 
# after adding the new load
after_lines_ft2 = net.res_line.loc[lines_to_ft2.index]
after_lines_t3 = net.res_line.loc[lines_to_t3.index]

print("Results for lines at FT2:\n", after_lines_ft2)
print("Results for lines at T3:\n", after_lines_t3)

Results for lines at FT2:
      p_from_mw  q_from_mvar  p_to_mw  q_to_mvar  pl_mw  ql_mvar  i_from_ka  \
343     0.9242       0.1845  -0.9242    -0.1851 0.0000  -0.0006     0.0192

     i_to_ka   i_ka  vm_from_pu  va_from_degree  vm_to_pu  va_to_degree  \
343   0.0192 0.0192      0.8590        -19.0755    0.8590      -19.0765

     loading_percent
343              NaN
Results for lines at T3:
      p_from_mw  q_from_mvar  p_to_mw  q_to_mvar  pl_mw  ql_mvar  i_from_ka  \
358     0.9242       0.1845  -0.9242    -0.1851 0.0000  -0.0006     0.0192

     i_to_ka   i_ka  vm_from_pu  va_from_degree  vm_to_pu  va_to_degree  \
358   0.0192 0.0192      0.8590        -19.0755    0.8590      -19.0765

     loading_percent
358              NaN

#### Comparison of the results before and after connecting the 1MW load to BARW52 busbar.

In [249]:
barw52_comparison = pd.DataFrame({
    "vm_pu_before": [before_BARW52["vm_pu"]],
    "vm_pu_after": [after_BARW52["vm_pu"]]
}, index=["BARW52"])

print("BARW52 voltage comparison (vm_pu):\n", barw52_comparison)

BARW52 voltage comparison (vm_pu):
         vm_pu_before  vm_pu_after
BARW52        0.9038       0.8960

In [250]:
trafo_comparison = pd.DataFrame({
    "loading_percent_before": [before_ft2["loading_percent"], before_t3["loading_percent"]],
    "loading_percent_after": [after_ft2["loading_percent"], after_t3["loading_percent"]]
}, index=["FT2", "T3"])

print("Trafo loading comparison (%):\n", trafo_comparison)

Trafo loading comparison (%):
      loading_percent_before  loading_percent_after
FT2                  3.9605                 6.0957
T3                   3.9605                 6.0957

In [251]:
line_comparison = pd.DataFrame({
    "loading_percent_before": [before_lines_ft2["loading_percent"].iloc[0], before_lines_t3["loading_percent"].iloc[0]],
    "loading_percent_after": [after_lines_ft2["loading_percent"].iloc[0], after_lines_t3["loading_percent"].iloc[0]],
    "p_from_mw_before": [before_lines_ft2["p_from_mw"].iloc[0], before_lines_t3["p_from_mw"].iloc[0]],
    "p_from_mw_after": [after_lines_ft2["p_from_mw"].iloc[0], after_lines_t3["p_from_mw"].iloc[0]],
    "q_from_mvar_before": [before_lines_ft2["q_from_mvar"].iloc[0], before_lines_t3["q_from_mvar"].iloc[0]],
    "q_from_mvar_after": [after_lines_ft2["q_from_mvar"].iloc[0], after_lines_t3["q_from_mvar"].iloc[0]]
}, index=["Line_FT2", "Line_T3"])

print("Line comparison:\n", line_comparison)

Line comparison:
           loading_percent_before  loading_percent_after  p_from_mw_before  \
Line_FT2                     NaN                    NaN            0.5906
Line_T3                      NaN                    NaN            0.5906

          p_from_mw_after  q_from_mvar_before  q_from_mvar_after
Line_FT2           0.9242              0.1797             0.1845
Line_T3            0.9242              0.1797             0.1845

## Add a new generator
A new static generator can be easily created with the *create_sgen" function of pandapower. It requires defining the bus to which the static generator will be connected and its active and reactive power.

In [252]:
# Create a new sgen at the desired bus
sgen_bus = BARW52_index

if sgen_bus not in net.bus.index:
    # if the bus not exists, it needs to be created first
    pp.create_bus(net, vn_kv=132, index=sgen_bus)
sgen_p = 0.3
sgen_q = 0
pp.create_sgen(net, bus=sgen_bus, p_mw=sgen_p, q_mvar=sgen_q)
net.sgen.tail(1)

,name,bus,p_mw,q_mvar,min_q_mvar,max_q_mvar,sn_mva,scaling,controllable,id_q_capability_characteristic,...,vn_kv,rdss_ohm,xdss_pu,lrc_pu,RegulatingControl.targetValue,referencePriority,max_p_mw,min_p_mw,RegulatingControl.enabled,vn_kv_bus
8,None,8287,0.3000,0.0000,NaN,NaN,NaN,1.0000,False,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN

## Run a headroom capacity analysis
It is possible to run a hosting capacity study and understand how much load or generation can be connected to a particular node, by incrementing continuously the power (of the load or generator) till when the boundaries of interest are not exceeded.

In this example, for simplicity, we will investigate how much load can be added to the desired bus before exceeding the loading capacity of the grid transformers.

In [253]:
if license_area == "LPN":
    hosting_bus = 18
elif license_area == "SPN":
    hosting_bus = 36
elif license_area == "EPN":
    hosting_bus = 20
else:
    hosting_bus = 0             # bus selected for the analysis
            # bus selected for the analysis
incremental_p_mw = 1        # incremental value of power
if hosting_bus not in net.bus.index:
    print("The given bus does not exist")
    hosting_bus = net.bus.index[0]   # replace the bus with the first bus in the grid
load_index = pp.create_load(net, bus=hosting_bus, p_mw=0, q_mvar=0)
within_hosting_limit = True    # boolean telling if we are still within inside the allowed boundary

# Hosting capacity logic
while within_hosting_limit:
    net.load.loc[load_index, "p_mw"] += incremental_p_mw
    pp.runpp(net, max_iteration=50)
    if np.any(net.res_trafo.loading_percent > 120) or net.trafo.index.size == 0:
        within_hosting_limit = False
        net.load.loc[load_index, "p_mw"] -= incremental_p_mw

# Visualize maximum load that can be connected at the selected bus
display("Maximum load that can be connected at bus " + str(hosting_bus) + " is " + str(net.load.loc[load_index, "p_mw"]) + " MW")

'Maximum load that can be connected at bus 18 is 58.0 MW'